// D-4: the one-click install links in README.md and docs/index.html must be
// exactly what scripts/install-links.mjs generates from package.json, so a
// package rename or a hand edit cannot leave a broken deeplink behind.
import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  SERVER_NAME,
  htmlEscape,
  installLinks,
  serverConfig,
} from "../scripts/install-links.mjs";

const root = fileURLToPath(new URL("..", import.meta.url));
const read = (rel) => readFileSync(path.join(root, rel), "utf8");
const pkg = JSON.parse(read("package.json"));
const links = installLinks(pkg);

test("install links: every generated string appears in README.md", () => {
  const readme = read("README.md");
  for (const [key, value] of Object.entries(links)) {
    if (key === "vscodeJson") continue; // embedded in codeAddMcp
    assert.ok(readme.includes(value), `README.md is missing ${key}: ${value}`);
  }
});

test("install links: every generated string appears in docs/index.html", () => {
  const html = read("docs/index.html");
  for (const [key, value] of Object.entries(links)) {
    if (key === "vscodeJson") continue;
    assert.ok(
      html.includes(htmlEscape(value)),
      `docs/index.html is missing ${key}: ${htmlEscape(value)}`,
    );
  }
});

test("install links: no stale deeplink survives in README.md or the site", () => {
  const pattern =
    /(?:vscode(?:-insiders)?:mcp\/install\?|cursor:\/\/anysphere\.cursor-deeplink\/mcp\/install\?|insiders\.vscode\.dev\/redirect\?url=|cursor\.com\/en\/install-mcp\?)[^\s)"'<`]+/g;
  const allowed = new Set(
    Object.values(links).flatMap((v) => [v, htmlEscape(v)]),
  );
  for (const file of ["README.md", "docs/index.html"]) {
    for (const match of read(file).matchAll(pattern)) {
      const found = match[0];
      const known = [...allowed].some((v) => v.endsWith(found));
      assert.ok(
        known,
        `${file} has a link not generated by the script: ${found}`,
      );
    }
  }
});

test("install links: payloads decode back to the npx launch config", () => {
  const expected = { command: "npx", args: ["-y", pkg.name] };
  assert.deepEqual(serverConfig(pkg), expected);

  const vscodeCfg = JSON.parse(
    decodeURIComponent(links.vscode.slice("vscode:mcp/install?".length)),
  );
  assert.deepEqual(vscodeCfg, { name: SERVER_NAME, ...expected });
  assert.equal(
    decodeURIComponent(new URL(links.vscodeWeb).searchParams.get("url")),
    decodeURIComponent(links.vscode),
  );

  const cursor = new URL(links.cursor);
  assert.equal(cursor.searchParams.get("name"), SERVER_NAME);
  const cursorCfg = JSON.parse(
    Buffer.from(cursor.searchParams.get("config"), "base64").toString("utf8"),
  );
  assert.deepEqual(cursorCfg, expected);
  assert.equal(
    new URL(links.cursorWeb).search,
    cursor.search,
    "the web and cursor:// links carry the same query",
  );
});

test("install links: the Claude Code plugin launches the same command", () => {
  const plugin = JSON.parse(read(".claude-plugin/plugin.json"));
  assert.deepEqual(plugin.mcpServers[SERVER_NAME], serverConfig(pkg));
});

test("install links: htmlEscape escapes markup but keeps quotes", () => {
  assert.equal(htmlEscape(`a&b<c>"d"`), `a&amp;b&lt;c&gt;"d"`);
});
