/** The script-bearing rows: the nine legacy script types first, then the S-4 tables. Part of ARTIFACT_TYPES, in registry order. */

import {
  type ArtifactType,
  BASE,
  EXPLAINED_SCRIPT_TIERS,
  SCRIPT_TOOL_TIERS,
  SEED_TIERS,
} from "./registry-model.js";

export const SCRIPT_ROWS: readonly ArtifactType[] = [
  // -- The nine script types behind list_scripts / search_code / … ----------
  // Order matters: SCRIPT_TYPES keeps it, and so do tool enums and reports.
  {
    ...BASE,
    type: "business_rule",
    group: "server",
    sdkApi: "BusinessRule",
    sdkSince: "<=3.0",
    table: "sys_script",
    nameField: "name",
    activeField: "active",
    scriptFields: ["script"],
    tiers: EXPLAINED_SCRIPT_TIERS,
    verified: true,
    scriptTools: true,
    appliesToField: "collection",
    // `global` marks the rules that run on every table (S-1: the table-flow
    // diagram lists them alongside the inherited ones).
    metaFields: [
      "collection",
      "global",
      "when",
      "order",
      "active",
      "condition",
    ],
  },
  {
    ...BASE,
    type: "script_include",
    group: "server",
    sdkApi: "ScriptInclude",
    sdkSince: "4.0",
    table: "sys_script_include",
    nameField: "name",
    keyFields: ["api_name"],
    activeField: "active",
    scriptFields: ["script"],
    tiers: EXPLAINED_SCRIPT_TIERS,
    verified: true,
    scriptTools: true,
    metaFields: ["api_name", "client_callable", "access", "active"],
  },
  {
    ...BASE,
    type: "client_script",
    group: "classic-ui",
    sdkApi: "ClientScript",
    sdkSince: "<=3.0",
    table: "sys_script_client",
    nameField: "name",
    activeField: "active",
    scriptFields: ["script"],
    clientFields: ["script"],
    tiers: EXPLAINED_SCRIPT_TIERS,
    verified: true,
    scriptTools: true,
    appliesToField: "table",
    metaFields: ["table", "type", "ui_type", "field", "active"],
    whenFields: ["type", "field", "ui_type", "condition"],
  },
  {
    ...BASE,
    type: "ui_policy",
    group: "classic-ui",
    sdkApi: "UiPolicy",
    sdkSince: "4.2",
    table: "sys_ui_policy",
    // servicenow_get_artifact reads the actions (P-5); their names stay
    // unverified until O-5 confirms them on a live instance.
    children: [
      {
        table: "sys_ui_policy_action",
        parentField: "ui_policy",
        nameField: "field",
        // P-23: the action flags upsert_artifact may write (unverified, O-5).
        writeFields: [
          "table",
          "visible",
          "mandatory",
          "disabled",
          "cleared",
          "value",
          "value_action",
          "field_message",
          "field_message_type",
        ],
        verified: false,
      },
    ],
    nameField: "short_description",
    activeField: "active",
    scriptFields: ["script_true", "script_false"],
    clientFields: ["script_true", "script_false"],
    tiers: EXPLAINED_SCRIPT_TIERS,
    verified: true,
    scriptTools: true,
    appliesToField: "table",
    metaFields: ["table", "active", "run_scripts"],
    writeFields: [
      "conditions",
      "description",
      "global",
      "inherit",
      "on_load",
      "order",
      "reverse_if_false",
      "ui_type",
      "view",
      "isolate_script",
    ],
  },
  {
    ...BASE,
    type: "ui_action",
    group: "classic-ui",
    sdkApi: "UiAction",
    sdkSince: "4.0",
    table: "sys_ui_action",
    nameField: "name",
    activeField: "active",
    scriptFields: ["script"],
    tiers: EXPLAINED_SCRIPT_TIERS,
    verified: true,
    scriptTools: true,
    appliesToField: "table",
    metaFields: ["table", "action_name", "active", "client", "order"],
  },
  {
    ...BASE,
    type: "scheduled_job",
    group: "server",
    sdkApi: "ScheduledScript",
    sdkSince: "4.5",
    table: "sysauto_script",
    nameField: "name",
    activeField: "active",
    scriptFields: ["script"],
    tiers: EXPLAINED_SCRIPT_TIERS,
    verified: true,
    scriptTools: true,
    metaFields: ["active", "run_type", "run_time"],
  },
  {
    ...BASE,
    type: "transform",
    group: "server",
    sdkApi: "ImportSet",
    sdkSince: "4.2",
    table: "sys_transform_script",
    nameField: "map",
    activeField: "active",
    scriptFields: ["script"],
    refFields: [
      { field: "map", table: "sys_transform_map", type: "transform_map" },
    ],
    tiers: EXPLAINED_SCRIPT_TIERS,
    verified: true,
    scriptTools: true,
    metaFields: ["map", "when", "order"],
  },
  {
    ...BASE,
    type: "rest_operation",
    group: "server",
    sdkApi: "RestApi",
    sdkSince: "<=3.0",
    table: "sys_ws_operation",
    nameField: "name",
    activeField: "active",
    scriptFields: ["operation_script"],
    refFields: [
      {
        field: "web_service_definition",
        table: "sys_ws_definition",
        type: "rest_api",
      },
    ],
    tiers: EXPLAINED_SCRIPT_TIERS,
    verified: true,
    scriptTools: true,
    metaFields: [
      "web_service_definition",
      "http_method",
      "operation_uri",
      "active",
    ],
  },
  {
    ...BASE,
    type: "acl",
    group: "core",
    sdkApi: "Acl",
    sdkSince: "<=3.0",
    table: "sys_security_acl",
    children: [
      {
        table: "sys_security_acl_role",
        parentField: "sys_security_acl",
        refFields: [
          { field: "sys_user_role", table: "sys_user_role", type: "role" },
        ],
        verified: false,
      },
    ],
    nameField: "name",
    activeField: "active",
    scriptFields: ["script"],
    tiers: EXPLAINED_SCRIPT_TIERS,
    verified: true,
    scriptTools: true,
    metaFields: ["operation", "type", "active", "admin_overrides"],
  },

  // -- S-4: the widened script-tools view (all unverified until O-5) ---------
  // Appended after the nine so their order, enums and reports are unchanged.
  {
    ...BASE,
    type: "script_action",
    group: "server",
    sdkApi: "ScriptAction",
    sdkSince: "4.0",
    table: "sysevent_script_action",
    nameField: "name",
    activeField: "active",
    scriptFields: ["script"],
    tiers: EXPLAINED_SCRIPT_TIERS,
    verified: false,
    scriptTools: true,
    metaFields: ["event_name", "order", "active"],
  },
  {
    ...BASE,
    type: "transform_map",
    group: "server",
    sdkApi: "ImportSet",
    sdkSince: "4.2",
    table: "sys_transform_map",
    children: [
      {
        table: "sys_transform_entry",
        parentField: "map",
        nameField: "target_field",
        scriptFields: ["source_script"],
      },
      {
        table: "sys_transform_script",
        parentField: "map",
        orderField: "order",
        scriptFields: ["script"],
      },
    ],
    nameField: "name",
    activeField: "active",
    // The map-level script runs only when `run_script` is set.
    scriptFields: ["script"],
    tiers: EXPLAINED_SCRIPT_TIERS,
    verified: false,
    scriptTools: true,
    appliesToField: "target_table",
    metaFields: ["source_table", "target_table", "run_script", "active"],
  },
  {
    ...BASE,
    type: "transform_entry",
    group: "server",
    sdkApi: "ImportSet",
    sdkSince: "4.2",
    table: "sys_transform_entry",
    nameField: "target_field",
    scriptFields: ["source_script"],
    refFields: [
      { field: "map", table: "sys_transform_map", type: "transform_map" },
    ],
    tiers: EXPLAINED_SCRIPT_TIERS,
    verified: false,
    scriptTools: true,
    metaFields: [
      "map",
      "source_field",
      "target_table",
      "target_field",
      "use_source_script",
    ],
  },
  {
    ...BASE,
    type: "fix_script",
    group: "server",
    sdkApi: "none",
    sdkSince: null,
    table: "sys_script_fix",
    nameField: "name",
    scriptFields: ["script"],
    tiers: EXPLAINED_SCRIPT_TIERS,
    verified: false,
    scriptTools: true,
    metaFields: ["description"],
  },
  {
    ...BASE,
    type: "email_script",
    group: "server",
    sdkApi: "none",
    sdkSince: null,
    table: "sys_script_email",
    nameField: "name",
    scriptFields: ["script"],
    tiers: EXPLAINED_SCRIPT_TIERS,
    verified: false,
    scriptTools: true,
    metaFields: [],
  },
  {
    ...BASE,
    type: "processor",
    group: "server",
    sdkApi: "none",
    sdkSince: null,
    table: "sys_processor",
    nameField: "name",
    activeField: "active",
    scriptFields: ["script"],
    tiers: EXPLAINED_SCRIPT_TIERS,
    verified: false,
    scriptTools: true,
    metaFields: ["path", "type", "active"],
  },
  {
    ...BASE,
    type: "data_source",
    group: "server",
    sdkApi: "none",
    sdkSince: null,
    table: "sys_data_source",
    nameField: "name",
    // `data_loader` backs "Custom (Load by Script)", `parsing_script` the
    // "Custom (Parse by Script)" file format.
    scriptFields: ["data_loader", "parsing_script"],
    tiers: EXPLAINED_SCRIPT_TIERS,
    verified: false,
    scriptTools: true,
    metaFields: ["type", "format", "import_set_table_name"],
  },
  {
    ...BASE,
    type: "rest_message_fn",
    group: "server",
    sdkApi: "RestMessage",
    sdkSince: null,
    table: "sys_rest_message_fn",
    nameField: "function_name",
    // Not JavaScript: the endpoint and body templates carry `${variable}`
    // substitutions, so they are searched but never linted.
    scriptFields: ["rest_endpoint", "content"],
    markupFields: ["rest_endpoint", "content"],
    refFields: [{ field: "rest_message", table: "sys_rest_message" }],
    tiers: EXPLAINED_SCRIPT_TIERS,
    verified: false,
    scriptTools: true,
    metaFields: ["rest_message", "http_method", "rest_endpoint"],
  },
  // Classic UI
  {
    ...BASE,
    type: "ui_script",
    group: "classic-ui",
    sdkApi: "none",
    sdkSince: null,
    table: "sys_ui_script",
    nameField: "name",
    activeField: "active",
    scriptFields: ["script"],
    clientFields: ["script"],
    tiers: EXPLAINED_SCRIPT_TIERS,
    verified: false,
    scriptTools: true,
    metaFields: ["global", "ui_type", "active"],
  },
  {
    ...BASE,
    type: "ui_page",
    group: "classic-ui",
    sdkApi: "UiPage",
    sdkSince: "4.0",
    table: "sys_ui_page",
    nameField: "name",
    keyFields: ["name"],
    // `html` is Jelly and routinely embeds <g:evaluate> server script.
    scriptFields: ["html", "client_script", "processing_script"],
    clientFields: ["client_script"],
    markupFields: ["html"],
    tiers: EXPLAINED_SCRIPT_TIERS,
    verified: false,
    scriptTools: true,
    metaFields: ["category", "description"],
  },
  {
    ...BASE,
    type: "ui_macro",
    group: "classic-ui",
    sdkApi: "none",
    sdkSince: null,
    table: "sys_ui_macro",
    nameField: "name",
    activeField: "active",
    // Jelly XML: searched for embedded script and references, not linted.
    scriptFields: ["xml"],
    markupFields: ["xml"],
    tiers: EXPLAINED_SCRIPT_TIERS,
    verified: false,
    scriptTools: true,
    metaFields: ["description", "active"],
  },
  {
    ...BASE,
    type: "validation_script",
    group: "classic-ui",
    sdkApi: "none",
    sdkSince: null,
    table: "sys_script_validator",
    // The table has no name field; the description is what lists show.
    nameField: "description",
    activeField: "active",
    scriptFields: ["validator"],
    clientFields: ["validator"],
    tiers: EXPLAINED_SCRIPT_TIERS,
    verified: false,
    scriptTools: true,
    metaFields: ["internal_type", "ui_type", "active"],
  },
  // Service Portal
  {
    ...BASE,
    type: "sp_widget",
    group: "portal",
    sdkApi: "SPWidget",
    sdkSince: "4.0",
    table: "sp_widget",
    children: [
      {
        table: "sp_ng_template",
        parentField: "sp_widget",
        nameField: "id",
        // P-24: the Angular template body; ids are unique instance-wide.
        writeFields: ["template"],
        unique: [{ fields: ["id"] }],
      },
      {
        table: "m2m_sp_widget_dependency",
        parentField: "sp_widget",
        // P-24 (U): the dependency the widget loads.
        writeFields: ["sp_dependency"],
      },
      {
        table: "m2m_sp_ng_pro_sp_widget",
        parentField: "sp_widget",
        refFields: [
          {
            field: "sp_angular_provider",
            table: "sp_angular_provider",
            type: "sp_angular_provider",
          },
        ],
      },
    ],
    nameField: "name",
    keyFields: ["id"],
    // `script` is the server script; the client controller and the link
    // function run in the browser; `css` is SCSS.
    scriptFields: ["script", "client_script", "link", "css"],
    clientFields: ["client_script", "link"],
    markupFields: ["css"],
    jsonFields: [
      { field: "option_schema", decoder: "json", writable: true },
      { field: "demo_data", decoder: "json", writable: true },
    ],
    tiers: SCRIPT_TOOL_TIERS,
    verified: false,
    scriptTools: true,
    metaFields: ["id", "data_table"],
    // P-24 (U, O-5): SP-2 fields upsert_artifact may write, SDK pre-flight.
    writeFields: [
      "template",
      "controller_as",
      "description",
      "public",
      "roles",
      "has_preview",
    ],
    unique: [{ fields: ["id"] }],
    scopePrefixFields: ["id"],
  },
  // Service Catalog
  {
    ...BASE,
    type: "catalog_client_script",
    group: "catalog",
    sdkApi: "CatalogClientScript",
    sdkSince: null,
    table: "catalog_script_client",
    nameField: "name",
    activeField: "active",
    scriptFields: ["script"],
    clientFields: ["script"],
    refFields: [
      { field: "cat_item", table: "sc_cat_item", type: "catalog_item" },
      {
        field: "variable_set",
        table: "item_option_new_set",
        type: "variable_set",
      },
    ],
    // P-8: also explained (X).
    tiers: EXPLAINED_SCRIPT_TIERS,
    verified: false,
    scriptTools: true,
    metaFields: ["cat_item", "variable_set", "type", "ui_type", "active"],
    whenFields: ["type", "cat_variable", "ui_type"],
  },
  // Data model
  {
    ...BASE,
    type: "dictionary_script",
    group: "core",
    sdkApi: "Table",
    sdkSince: null,
    table: "sys_dictionary",
    // Only calculated columns (`virtual` is the "Calculated" flag) and
    // scripted defaults; plain dictionary entries are not script artefacts.
    baseQuery: "virtual=true^ORdefault_valueSTARTSWITHjavascript:",
    nameField: "element",
    keyFields: ["name", "element"],
    activeField: "active",
    scriptFields: ["calculation", "default_value"],
    tiers: EXPLAINED_SCRIPT_TIERS,
    verified: false,
    scriptTools: true,
    appliesToField: "name",
    metaFields: ["name", "internal_type", "virtual", "active"],
  },

  // -- Seeds (not exposed through any tool yet; all unverified until O-5) ----
  // Server-side logic
  {
    ...BASE,
    type: "rest_api",
    group: "server",
    sdkApi: "RestApi",
    sdkSince: "<=3.0",
    table: "sys_ws_definition",
    children: [
      {
        table: "sys_ws_operation",
        parentField: "web_service_definition",
        nameField: "name",
        scriptFields: ["operation_script"],
      },
      { table: "sys_ws_version", parentField: "web_service_definition" },
    ],
    nameField: "name",
    activeField: "active",
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
  },
];
