/** UI Builder and Service Portal rows. Part of ARTIFACT_TYPES, in registry order. */

import { type ArtifactType, BASE, READ_TIER } from "./registry-model.js";

export const UI_TYPES: readonly ArtifactType[] = [
  // UI Builder internals (no Fluent API: `Record()`; SDK-PARITY §4.5)
  {
    ...BASE,
    type: "uib_app_config",
    group: "uib",
    sdkApi: "Record",
    sdkSince: null,
    table: "sys_ux_app_config",
    children: [
      {
        table: "sys_ux_app_route",
        parentField: "app_config",
        nameField: "name",
        jsonFields: [{ field: "parameters", decoder: "json", writable: false }],
        refFields: [
          {
            field: "parent_macroponent",
            table: "sys_ux_macroponent",
            type: "uib_macroponent",
          },
        ],
      },
    ],
    nameField: "name",
    scriptFields: [],
    tiers: READ_TIER,
    verified: false,
  },
  {
    ...BASE,
    type: "uib_route",
    group: "uib",
    sdkApi: "Record",
    sdkSince: null,
    table: "sys_ux_app_route",
    nameField: "name",
    scriptFields: [],
    jsonFields: [
      { field: "parameters", decoder: "json", writable: false },
      { field: "optional_parameters", decoder: "json", writable: false },
    ],
    refFields: [
      {
        field: "app_config",
        table: "sys_ux_app_config",
        type: "uib_app_config",
      },
      {
        field: "screen_type",
        table: "sys_ux_screen_type",
        type: "uib_screen_type",
      },
      {
        field: "parent_macroponent",
        table: "sys_ux_macroponent",
        type: "uib_macroponent",
      },
    ],
    tiers: READ_TIER,
    verified: false,
  },
  {
    ...BASE,
    type: "uib_screen_type",
    group: "uib",
    sdkApi: "Record",
    sdkSince: null,
    table: "sys_ux_screen_type",
    // Page variants: one screen per audience / condition, ordered.
    children: [
      {
        table: "sys_ux_screen",
        parentField: "screen_type",
        orderField: "order",
        nameField: "name",
        jsonFields: [
          { field: "macroponent_config", decoder: "json", writable: false },
          { field: "event_mappings", decoder: "json", writable: false },
        ],
        refFields: [
          {
            field: "macroponent",
            table: "sys_ux_macroponent",
            type: "uib_macroponent",
          },
        ],
      },
    ],
    nameField: "name",
    scriptFields: [],
    tiers: READ_TIER,
    verified: false,
  },
  {
    ...BASE,
    type: "uib_screen",
    group: "uib",
    sdkApi: "Record",
    sdkSince: null,
    table: "sys_ux_screen",
    children: [{ table: "sys_ux_screen_condition", parentField: "screen" }],
    nameField: "name",
    scriptFields: [],
    jsonFields: [
      { field: "macroponent_config", decoder: "json", writable: false },
      { field: "event_mappings", decoder: "json", writable: false },
    ],
    refFields: [
      {
        field: "screen_type",
        table: "sys_ux_screen_type",
        type: "uib_screen_type",
      },
      {
        field: "macroponent",
        table: "sys_ux_macroponent",
        type: "uib_macroponent",
      },
      {
        field: "app_config",
        table: "sys_ux_app_config",
        type: "uib_app_config",
      },
      { field: "applicability", table: "sys_ux_applicability" },
    ],
    tiers: READ_TIER,
    verified: false,
  },
  {
    ...BASE,
    type: "uib_macroponent",
    group: "uib",
    sdkApi: "Record",
    sdkSince: null,
    table: "sys_ux_macroponent",
    children: [
      {
        table: "sys_ux_client_script",
        parentField: "macroponent",
        nameField: "name",
        scriptFields: ["script"],
      },
    ],
    nameField: "name",
    scriptFields: [],
    // UIB layout JSON is plan-only until a round-trip test exists (§5(c)).
    jsonFields: [
      { field: "composition", decoder: "uib-composition", writable: false },
      { field: "data", decoder: "json", writable: false },
      { field: "props", decoder: "json", writable: false },
      { field: "internal_event_mappings", decoder: "json", writable: false },
      { field: "state_properties", decoder: "json", writable: false },
      { field: "dispatched_events", decoder: "json", writable: false },
      { field: "handled_events", decoder: "json", writable: false },
      { field: "required_translations", decoder: "json", writable: false },
    ],
    tiers: READ_TIER,
    verified: false,
  },
  // UI Builder client scripts and data brokers carry code: opt-in script
  // tools (see `scriptToolsOptIn`).
  {
    ...BASE,
    type: "uib_client_script",
    group: "uib",
    sdkApi: "Record",
    sdkSince: null,
    table: "sys_ux_client_script",
    nameField: "name",
    scriptFields: ["script"],
    clientFields: ["script"],
    refFields: [
      {
        field: "macroponent",
        table: "sys_ux_macroponent",
        type: "uib_macroponent",
      },
    ],
    tiers: READ_TIER,
    verified: false,
    scriptToolsOptIn: true,
    metaFields: ["macroponent", "type"],
  },
  {
    ...BASE,
    type: "uib_client_script_include",
    group: "uib",
    sdkApi: "Record",
    sdkSince: null,
    table: "sys_ux_client_script_include",
    nameField: "name",
    scriptFields: ["script"],
    clientFields: ["script"],
    tiers: READ_TIER,
    verified: false,
    scriptToolsOptIn: true,
    metaFields: [],
  },
  {
    ...BASE,
    type: "uib_data_broker_transform",
    group: "uib",
    sdkApi: "Record",
    sdkSince: null,
    table: "sys_ux_data_broker_transform",
    nameField: "name",
    // Server-side transform; `properties` is the broker's input schema.
    scriptFields: ["script"],
    jsonFields: [{ field: "properties", decoder: "json", writable: false }],
    tiers: READ_TIER,
    verified: false,
    scriptToolsOptIn: true,
    metaFields: ["mutates_server_data"],
  },
  {
    ...BASE,
    type: "uib_data_broker_scriptlet",
    group: "uib",
    sdkApi: "Record",
    sdkSince: null,
    table: "sys_ux_data_broker_scriptlet",
    nameField: "name",
    // Client-side scriptlet: runs in the browser.
    scriptFields: ["script"],
    clientFields: ["script"],
    jsonFields: [{ field: "properties", decoder: "json", writable: false }],
    tiers: READ_TIER,
    verified: false,
    scriptToolsOptIn: true,
    metaFields: [],
  },
  {
    ...BASE,
    type: "uib_event",
    group: "uib",
    sdkApi: "Record",
    sdkSince: null,
    table: "sys_ux_event",
    nameField: "label",
    keyFields: ["name"],
    scriptFields: [],
    jsonFields: [{ field: "props", decoder: "json", writable: false }],
    tiers: READ_TIER,
    verified: false,
  },
  {
    ...BASE,
    type: "uib_component",
    group: "uib",
    sdkApi: "Record",
    sdkSince: null,
    table: "sys_ux_lib_component",
    nameField: "name",
    keyFields: ["tag"],
    scriptFields: [],
    jsonFields: [{ field: "properties", decoder: "json", writable: false }],
    tiers: READ_TIER,
    verified: false,
  },
  {
    ...BASE,
    type: "uib_theme",
    group: "uib",
    sdkApi: "Record",
    sdkSince: null,
    table: "sys_ux_theme",
    nameField: "name",
    scriptFields: [],
    tiers: READ_TIER,
    verified: false,
  },
  {
    ...BASE,
    type: "uib_style",
    group: "uib",
    sdkApi: "Record",
    sdkSince: null,
    table: "sys_ux_style",
    nameField: "name",
    scriptFields: [],
    jsonFields: [{ field: "style", decoder: "json", writable: false }],
    tiers: READ_TIER,
    verified: false,
  },
  {
    ...BASE,
    type: "uib_form_action",
    group: "uib",
    sdkApi: "Record",
    sdkSince: null,
    table: "sys_ux_form_action",
    nameField: "label",
    scriptFields: [],
    refFields: [
      { field: "action", table: "sys_ui_action" },
      { field: "applicability", table: "sys_ux_applicability" },
    ],
    tiers: READ_TIER,
    verified: false,
  },
  {
    ...BASE,
    type: "uib_form_action_layout",
    group: "uib",
    sdkApi: "Record",
    sdkSince: null,
    table: "sys_ux_form_action_layout",
    children: [
      {
        table: "sys_ux_form_action_layout_item",
        parentField: "form_action_layout",
        orderField: "order",
        refFields: [
          {
            field: "form_action",
            table: "sys_ux_form_action",
            type: "uib_form_action",
          },
        ],
      },
    ],
    nameField: "name",
    scriptFields: [],
    tiers: READ_TIER,
    verified: false,
  },
  {
    ...BASE,
    type: "uib_composite_definition",
    group: "uib",
    sdkApi: "Record",
    sdkSince: null,
    table: "sys_ux_composite_definition",
    nameField: "name",
    scriptFields: [],
    tiers: READ_TIER,
    verified: false,
  },
  // N-29: REST and GraphQL data brokers. Neither table is in the SDK
  // inventory; table and field names are unverified until O-5 (PDI). No
  // script fields (a GraphQL query is not JavaScript), so no script-tools
  // opt-in (no enum growth).
  {
    ...BASE,
    type: "uib_data_broker_rest",
    group: "uib",
    sdkApi: "Record",
    sdkSince: null,
    table: "sys_ux_data_broker_rest",
    nameField: "name",
    scriptFields: [],
    jsonFields: [{ field: "properties", decoder: "json", writable: false }],
    tiers: READ_TIER,
    verified: false,
    metaFields: ["mutates_server_data"],
  },
  {
    ...BASE,
    type: "uib_data_broker_graphql",
    group: "uib",
    sdkApi: "Record",
    sdkSince: null,
    table: "sys_ux_data_broker_graphql",
    nameField: "name",
    scriptFields: [],
    jsonFields: [{ field: "properties", decoder: "json", writable: false }],
    tiers: READ_TIER,
    verified: false,
    metaFields: ["mutates_server_data"],
  },
  // N-30: the declarative action, theme and Agent Workspace tables that
  // src/api/uib-workspace.ts reads. `sys_declarative_action_assignment` is in
  // the SDK table inventory (no Fluent API); the other tables and their
  // fields are unverified until O-5 (PDI). The assignment scripts are script
  // fields, but not a script-tools type: list_scripts / search_code do not
  // sweep them (no enum growth).
  {
    ...BASE,
    type: "ux_declarative_action",
    group: "uib",
    sdkApi: "Record",
    sdkSince: null,
    table: "sys_declarative_action_assignment",
    nameField: "label",
    keyFields: ["action_name"],
    activeField: "active",
    scriptFields: ["server_script", "client_script"],
    clientFields: ["client_script"],
    refFields: [
      {
        field: "client_action",
        table: "sys_declarative_action_payload_definition",
        type: "ux_declarative_action_payload",
      },
      {
        field: "action",
        table: "sys_declarative_action_definition",
        type: "ux_declarative_action_definition",
      },
      {
        field: "ui_component",
        table: "sys_ux_lib_component",
        type: "uib_component",
      },
      { field: "model", table: "sys_declarative_action_model_definition" },
      {
        field: "workspace",
        table: "sys_aw_master_config",
        type: "aw_master_config",
      },
      { field: "view", table: "sys_ui_view", type: "ui_view" },
      { field: "required_roles", table: "sys_user_role", type: "role" },
    ],
    tiers: READ_TIER,
    verified: false,
  },
  {
    ...BASE,
    type: "ux_declarative_action_definition",
    group: "uib",
    sdkApi: "Record",
    sdkSince: null,
    table: "sys_declarative_action_definition",
    nameField: "label",
    keyFields: ["action_name"],
    scriptFields: [],
    tiers: READ_TIER,
    verified: false,
  },
  {
    ...BASE,
    type: "ux_declarative_action_payload",
    group: "uib",
    sdkApi: "Record",
    sdkSince: null,
    table: "sys_declarative_action_payload_definition",
    nameField: "label",
    keyFields: ["key"],
    scriptFields: [],
    jsonFields: [{ field: "payload", decoder: "json", writable: false }],
    tiers: READ_TIER,
    verified: false,
  },
  {
    ...BASE,
    type: "uib_app_theme",
    group: "uib",
    sdkApi: "Record",
    sdkSince: null,
    table: "m2m_app_theme",
    // A many-to-many row has no name of its own: the theme reference names it.
    nameField: "theme",
    scriptFields: [],
    refFields: [{ field: "theme", table: "sys_ux_theme", type: "uib_theme" }],
    tiers: READ_TIER,
    verified: false,
  },
  {
    ...BASE,
    type: "aw_master_config",
    group: "uib",
    sdkApi: "Record",
    sdkSince: null,
    table: "sys_aw_master_config",
    nameField: "name",
    scriptFields: [],
    tiers: READ_TIER,
    verified: false,
  },
  {
    ...BASE,
    type: "aw_list",
    group: "uib",
    sdkApi: "Record",
    sdkSince: null,
    table: "sys_aw_list",
    nameField: "title",
    keyFields: ["table"],
    scriptFields: [],
    tiers: READ_TIER,
    verified: false,
  },
  // Service Portal (SDK-PARITY §4.6; `sp_widget` itself is in the S-4 view)
  {
    ...BASE,
    type: "sp_portal",
    group: "portal",
    sdkApi: "ServicePortal",
    sdkSince: null,
    table: "sp_portal",
    nameField: "title",
    keyFields: ["url_suffix"],
    refFields: [
      { field: "homepage", table: "sp_page", type: "sp_page" },
      { field: "login_page", table: "sp_page", type: "sp_page" },
      { field: "notfound_page", table: "sp_page", type: "sp_page" },
      { field: "theme", table: "sp_theme", type: "sp_theme" },
      {
        field: "sp_rectangle_menu",
        table: "sp_instance_menu",
        type: "sp_menu",
      },
    ],
    scriptFields: [],
    tiers: READ_TIER,
    verified: false,
    // P-24 (U, O-5).
    writeFields: ["quick_start_config", "default", "logo", "icon"],
    unique: [{ fields: ["url_suffix"] }],
  },
  {
    ...BASE,
    type: "sp_page",
    group: "portal",
    sdkApi: "SPPage",
    sdkSince: "4.5",
    table: "sp_page",
    // Layout: page → containers → rows → columns → widget instances.
    // P-24: upsert_artifact writes the whole tree as one plan; each nested
    // child names its parent child by position (`parent`). The layout field
    // names beyond the links, `order` and `widget_parameters` are (U), O-5.
    children: [
      {
        table: "sp_container",
        parentField: "sp_page",
        orderField: "order",
        writeFields: [
          "name",
          "width",
          "background_color",
          "background_image",
          "class_name",
        ],
      },
      {
        table: "sp_row",
        parentField: "sp_container",
        parentTable: "sp_container",
        orderField: "order",
        writeFields: ["class_name"],
      },
      {
        table: "sp_column",
        parentField: "sp_row",
        parentTable: "sp_row",
        orderField: "order",
        writeFields: ["size", "class_name"],
      },
      {
        table: "sp_instance",
        parentField: "sp_column",
        parentTable: "sp_column",
        orderField: "order",
        jsonFields: [
          { field: "widget_parameters", decoder: "json", writable: true },
        ],
        refFields: [
          { field: "sp_widget", table: "sp_widget", type: "sp_widget" },
        ],
        writeFields: [
          "title",
          "class_name",
          "css",
          "color",
          "size",
          "roles",
          "short_description",
          "active",
        ],
      },
    ],
    nameField: "title",
    keyFields: ["id"],
    scriptFields: [],
    tiers: READ_TIER,
    verified: false,
    writeFields: ["public", "roles", "draft", "short_description", "internal"],
    unique: [{ fields: ["id"] }],
    scopePrefixFields: ["id"],
  },
  {
    ...BASE,
    type: "sp_ng_template",
    group: "portal",
    sdkApi: "SPWidget",
    sdkSince: "4.0",
    table: "sp_ng_template",
    nameField: "id",
    keyFields: ["id"],
    // Angular HTML template: searched, never linted.
    scriptFields: ["template"],
    markupFields: ["template"],
    refFields: [{ field: "sp_widget", table: "sp_widget", type: "sp_widget" }],
    tiers: READ_TIER,
    verified: false,
    scriptToolsOptIn: true,
    metaFields: ["sp_widget"],
    unique: [{ fields: ["id"] }],
    scopePrefixFields: ["id"],
  },
  {
    ...BASE,
    type: "sp_dependency",
    group: "portal",
    sdkApi: "SPWidgetDependency",
    sdkSince: null,
    table: "sp_dependency",
    children: [
      {
        table: "m2m_sp_dependency_js_include",
        parentField: "sp_dependency",
        orderField: "order",
        refFields: [
          {
            field: "sp_js_include",
            table: "sp_js_include",
            type: "sp_js_include",
          },
        ],
      },
      {
        table: "m2m_sp_dependency_css_include",
        parentField: "sp_dependency",
        orderField: "order",
        refFields: [
          {
            field: "sp_css_include",
            table: "sp_css_include",
            type: "sp_css_include",
          },
        ],
      },
    ],
    nameField: "name",
    scriptFields: [],
    tiers: READ_TIER,
    verified: false,
    // P-24 (U, O-5): SP-3 fields; `module` is the Angular module name.
    writeFields: ["module", "include_on_page_load"],
    unique: [{ fields: ["name"] }, { fields: ["module"] }],
  },
  {
    ...BASE,
    type: "sp_angular_provider",
    group: "portal",
    sdkApi: "SPAngularProvider",
    sdkSince: null,
    table: "sp_angular_provider",
    nameField: "name",
    keyFields: ["name"],
    // Directives, services and factories: all run in the browser.
    scriptFields: ["script"],
    clientFields: ["script"],
    tiers: READ_TIER,
    verified: false,
    scriptToolsOptIn: true,
    metaFields: ["type"],
    unique: [{ fields: ["name"] }],
  },
  {
    ...BASE,
    type: "sp_js_include",
    group: "portal",
    sdkApi: "JsInclude",
    sdkSince: null,
    table: "sp_js_include",
    nameField: "display_name",
    scriptFields: [],
    refFields: [
      { field: "sys_ui_script", table: "sys_ui_script", type: "ui_script" },
    ],
    tiers: READ_TIER,
    verified: false,
    // P-24 (U, O-5).
    writeFields: ["source", "url"],
  },
  {
    ...BASE,
    type: "sp_css_include",
    group: "portal",
    sdkApi: "CssInclude",
    sdkSince: null,
    table: "sp_css_include",
    nameField: "name",
    scriptFields: [],
    refFields: [{ field: "sp_css", table: "sp_css", type: "sp_css" }],
    tiers: READ_TIER,
    verified: false,
    // P-24 (U, O-5).
    writeFields: ["source", "url"],
  },
  {
    ...BASE,
    type: "sp_theme",
    group: "portal",
    sdkApi: "SPTheme",
    sdkSince: null,
    table: "sp_theme",
    children: [
      {
        table: "m2m_sp_theme_js_include",
        parentField: "sp_theme",
        orderField: "order",
        // P-24 (U, O-5).
        writeFields: ["sp_js_include"],
      },
      {
        table: "m2m_sp_theme_css_include",
        parentField: "sp_theme",
        orderField: "order",
        writeFields: ["sp_css_include"],
      },
    ],
    nameField: "name",
    // SCSS variables: searched, never linted.
    scriptFields: ["css_variables"],
    markupFields: ["css_variables"],
    refFields: [
      { field: "header", table: "sp_header_footer", type: "sp_header_footer" },
      { field: "footer", table: "sp_header_footer", type: "sp_header_footer" },
    ],
    tiers: READ_TIER,
    verified: false,
    scriptToolsOptIn: true,
    metaFields: ["header", "footer"],
  },
  {
    ...BASE,
    type: "sp_menu",
    group: "portal",
    sdkApi: "SPMenu",
    sdkSince: null,
    table: "sp_instance_menu",
    children: [
      {
        table: "sp_rectangle_menu_item",
        parentField: "sp_rectangle_menu",
        orderField: "order",
        nameField: "label",
        refFields: [{ field: "sp_page", table: "sp_page", type: "sp_page" }],
        // P-24 (U, O-5).
        writeFields: ["type", "url", "condition"],
      },
    ],
    nameField: "title",
    scriptFields: [],
    tiers: READ_TIER,
    verified: false,
  },
  {
    ...BASE,
    type: "sp_header_footer",
    group: "portal",
    sdkApi: "SPHeaderFooter",
    sdkSince: null,
    // Extends sp_widget, so the `sp_widget` script view already searches its
    // code; no script fields here to avoid duplicate hits.
    table: "sp_header_footer",
    nameField: "name",
    keyFields: ["id"],
    scriptFields: [],
    tiers: READ_TIER,
    verified: false,
    // P-24 (U, O-5): the widget fields it inherits; ids are unique across
    // sp_widget and every table extending it.
    writeFields: [
      "template",
      "css",
      "script",
      "client_script",
      "link",
      "controller_as",
    ],
    unique: [{ fields: ["id"], table: "sp_widget" }],
    scopePrefixFields: ["id"],
  },
  {
    ...BASE,
    type: "sp_page_route_map",
    group: "portal",
    sdkApi: "SPPageRouteMap",
    sdkSince: null,
    table: "sp_page_route_map",
    nameField: "short_description",
    activeField: "active",
    scriptFields: [],
    refFields: [
      { field: "route_from_page", table: "sp_page", type: "sp_page" },
      { field: "route_to_page", table: "sp_page", type: "sp_page" },
    ],
    tiers: READ_TIER,
    verified: false,
    // P-24 (U, O-5).
    writeFields: ["portals", "roles", "order"],
  },
  // Portal tables the SDK does not model (SP-11).
  {
    ...BASE,
    type: "sp_css",
    group: "portal",
    sdkApi: "none",
    sdkSince: null,
    table: "sp_css",
    nameField: "name",
    scriptFields: ["css"],
    markupFields: ["css"],
    tiers: READ_TIER,
    verified: false,
    scriptToolsOptIn: true,
    metaFields: [],
  },
  {
    ...BASE,
    type: "sp_search_source",
    group: "portal",
    sdkApi: "none",
    sdkSince: null,
    table: "sp_search_source",
    nameField: "name",
    keyFields: ["id"],
    // Server scripts of a scripted search source.
    scriptFields: ["data_fetch_script", "facet_generation_script"],
    tiers: READ_TIER,
    verified: false,
    scriptToolsOptIn: true,
    metaFields: ["id", "is_scripted_source"],
  },
];
