/** P-7 core, server-logic and classic-UI rows, then the Next Experience rows. Part of ARTIFACT_TYPES, in registry order. */

import {
  type ArtifactType,
  BASE,
  READ_TIER,
  SEED_TIERS,
} from "./registry-model.js";

export const PLATFORM_ROWS: readonly ArtifactType[] = [
  // -- P-7: core, server-logic and classic-UI rows (SDK-PARITY §4.1 – §4.3) --
  // All unverified until O-5: names come from the SDK inventory.
  // Core platform / data model
  {
    ...BASE,
    type: "table",
    group: "core",
    sdkApi: "Table",
    sdkSince: "<=3.0",
    table: "sys_db_object",
    // Columns, overrides, labels and choices hang off the table name.
    children: [
      {
        table: "sys_dictionary",
        parentField: "name",
        parentKey: "name",
        orderField: "element",
        nameField: "element",
      },
      {
        table: "sys_dictionary_override",
        parentField: "name",
        parentKey: "name",
        nameField: "element",
      },
      {
        table: "sys_documentation",
        parentField: "name",
        parentKey: "name",
        orderField: "element",
        nameField: "element",
      },
      {
        table: "sys_choice",
        parentField: "name",
        parentKey: "name",
        orderField: "element",
        nameField: "label",
      },
    ],
    nameField: "name",
    keyFields: ["name"],
    scriptFields: [],
    refFields: [
      { field: "super_class", table: "sys_db_object", type: "table" },
    ],
    tiers: SEED_TIERS,
    verified: false,
    metaFields: ["label", "super_class", "is_extendable"],
  },
  {
    ...BASE,
    type: "choice_set",
    group: "core",
    sdkApi: "ChoiceSet",
    sdkSince: null,
    table: "sys_choice_set",
    children: [
      {
        table: "sys_choice",
        parentField: "name",
        parentKey: "name",
        alsoMatch: [{ field: "element", parentKey: "element" }],
        orderField: "sequence",
        nameField: "label",
      },
    ],
    nameField: "element",
    keyFields: ["name", "element"],
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
    appliesToField: "name",
  },
  {
    ...BASE,
    type: "state_model",
    group: "core",
    sdkApi: "StateModel",
    sdkSince: "4.10",
    table: "sttrm_model",
    children: [
      { table: "sttrm_state", parentField: "model", nameField: "label" },
      {
        table: "sttrm_state_transition",
        parentField: "model",
        nameField: "name",
        refFields: [
          { field: "from_state", table: "sttrm_state" },
          { field: "to_state", table: "sttrm_state" },
        ],
      },
      {
        table: "sttrm_transition_condition",
        parentField: "transition",
        parentTable: "sttrm_state_transition",
      },
    ],
    nameField: "name",
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
    appliesToField: "table",
    metaFields: ["table", "state_field"],
  },
  {
    ...BASE,
    type: "property",
    group: "core",
    sdkApi: "Property",
    sdkSince: null,
    table: "sys_properties",
    nameField: "name",
    keyFields: ["name"],
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
    metaFields: ["type", "value", "is_private", "read_roles", "write_roles"],
  },
  {
    ...BASE,
    type: "user_preference",
    group: "core",
    sdkApi: "UserPreference",
    sdkSince: null,
    table: "sys_user_preference",
    nameField: "name",
    keyFields: ["name", "user"],
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
    metaFields: ["user", "value", "system"],
  },
  {
    ...BASE,
    type: "role",
    group: "core",
    sdkApi: "Role",
    sdkSince: null,
    table: "sys_user_role",
    children: [
      {
        table: "sys_user_role_contains",
        parentField: "role",
        refFields: [
          { field: "contains", table: "sys_user_role", type: "role" },
        ],
      },
    ],
    nameField: "name",
    keyFields: ["name"],
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
    metaFields: ["elevated_privilege", "assignable_by", "description"],
  },
  {
    ...BASE,
    type: "cross_scope_privilege",
    group: "core",
    sdkApi: "CrossScopePrivilege",
    sdkSince: null,
    table: "sys_scope_privilege",
    nameField: "target_name",
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
    metaFields: [
      "source_scope",
      "target_scope",
      "target_type",
      "operation",
      "status",
    ],
  },
  {
    ...BASE,
    type: "user_criteria",
    group: "core",
    sdkApi: "UserCriteria",
    sdkSince: null,
    table: "user_criteria",
    nameField: "name",
    activeField: "active",
    scriptFields: ["script"],
    tiers: SEED_TIERS,
    verified: false,
    metaFields: ["advanced", "match_all", "active"],
  },
  {
    ...BASE,
    type: "field_style",
    group: "core",
    sdkApi: "Record",
    sdkSince: null,
    table: "sys_ui_style",
    nameField: "element",
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
    appliesToField: "name",
    metaFields: ["name", "element", "value", "style"],
  },
  {
    ...BASE,
    type: "schedule",
    group: "core",
    sdkApi: "Record",
    sdkSince: null,
    table: "cmn_schedule",
    children: [
      {
        table: "cmn_schedule_span",
        parentField: "schedule",
        nameField: "name",
      },
    ],
    nameField: "name",
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
    metaFields: ["type", "time_zone"],
  },
  {
    ...BASE,
    type: "event",
    group: "core",
    sdkApi: "Record",
    sdkSince: null,
    table: "sysevent_register",
    nameField: "event_name",
    keyFields: ["event_name"],
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
    appliesToField: "table",
    metaFields: ["table", "fired_by", "queue", "description"],
  },
  {
    ...BASE,
    type: "relationship",
    group: "core",
    sdkApi: "Record",
    sdkSince: null,
    table: "sys_relationship",
    nameField: "name",
    scriptFields: ["query_with"],
    tiers: SEED_TIERS,
    verified: false,
    metaFields: ["basic_apply_to", "basic_query_from"],
  },
  {
    ...BASE,
    type: "ldap_server",
    group: "core",
    sdkApi: "Record",
    sdkSince: null,
    table: "ldap_server_config",
    children: [
      { table: "ldap_server_url", parentField: "server", orderField: "order" },
    ],
    nameField: "name",
    activeField: "active",
    scriptFields: [],
    secretFields: ["password"],
    tiers: SEED_TIERS,
    verified: false,
    metaFields: ["active", "dn", "ssl"],
  },
  // Server-side logic
  {
    ...BASE,
    type: "js_module",
    group: "server",
    sdkApi: "none",
    sdkSince: null,
    table: "sys_module",
    nameField: "name",
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
  },
  {
    ...BASE,
    type: "rest_message",
    group: "server",
    sdkApi: "RestMessage",
    sdkSince: "4.8",
    table: "sys_rest_message",
    children: [
      {
        table: "sys_rest_message_fn",
        parentField: "rest_message",
        nameField: "function_name",
      },
      {
        table: "sys_rest_message_headers",
        parentField: "rest_message",
        nameField: "name",
      },
      {
        table: "sys_rest_message_fn_parameters",
        parentField: "rest_message_function",
        parentTable: "sys_rest_message_fn",
        nameField: "name",
      },
      {
        table: "sys_rest_message_fn_headers",
        parentField: "rest_message_function",
        parentTable: "sys_rest_message_fn",
        nameField: "name",
      },
    ],
    nameField: "name",
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
    metaFields: ["rest_endpoint", "authentication_type", "use_mid_server"],
  },
  {
    ...BASE,
    type: "graphql_api",
    group: "server",
    sdkApi: "GraphQLApi",
    sdkSince: "4.11",
    table: "sys_graphql_schema",
    children: [
      {
        table: "sys_graphql_resolver",
        parentField: "schema",
        nameField: "name",
        scriptFields: ["script"],
      },
      {
        table: "sys_graphql_resolver_mapping",
        parentField: "schema",
        nameField: "path",
        refFields: [{ field: "resolver", table: "sys_graphql_resolver" }],
      },
      {
        table: "sys_graphql_typeresolver",
        parentField: "schema",
        nameField: "name",
        scriptFields: ["script"],
      },
    ],
    nameField: "name",
    activeField: "active",
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
    metaFields: ["schema_namespace", "requires_authentication", "active"],
  },
  {
    ...BASE,
    type: "alias",
    group: "server",
    sdkApi: "Alias",
    sdkSince: "4.8",
    table: "sys_alias",
    nameField: "name",
    scriptFields: [],
    refFields: [
      {
        field: "configuration_template",
        table: "sys_alias_templates",
        type: "alias_template",
      },
    ],
    tiers: SEED_TIERS,
    verified: false,
    metaFields: ["id", "type", "connection_type"],
  },
  {
    ...BASE,
    type: "alias_template",
    group: "server",
    sdkApi: "AliasTemplate",
    sdkSince: null,
    table: "sys_alias_templates",
    nameField: "name",
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
  },
  {
    ...BASE,
    type: "retry_policy",
    group: "server",
    sdkApi: "RetryPolicy",
    sdkSince: "4.8",
    table: "sys_retry_policy",
    nameField: "name",
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
  },
  {
    ...BASE,
    type: "data_lookup",
    group: "server",
    sdkApi: "DataLookup",
    sdkSince: "4.8",
    table: "dl_definition",
    // The matcher table itself (a dl_matcher extension) is named by
    // `matcher_table`, not linked as a child.
    children: [
      {
        table: "dl_definition_rel_match",
        parentField: "definition",
        nameField: "source_field",
      },
      {
        table: "dl_definition_rel_set",
        parentField: "definition",
        nameField: "target_field",
      },
    ],
    nameField: "name",
    activeField: "active",
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
    appliesToField: "table",
    metaFields: ["table", "matcher_table", "active"],
  },
  {
    ...BASE,
    type: "email_notification",
    group: "server",
    sdkApi: "EmailNotification",
    sdkSince: null,
    table: "sysevent_email_action",
    nameField: "name",
    activeField: "active",
    scriptFields: ["advanced_condition"],
    refFields: [{ field: "template", table: "sysevent_email_template" }],
    tiers: SEED_TIERS,
    verified: false,
    appliesToField: "collection",
    metaFields: ["collection", "generation_type", "event_name", "active"],
    whenFields: [
      "generation_type",
      "event_name",
      "action_insert",
      "action_update",
      "condition",
      "weight",
    ],
  },
  {
    ...BASE,
    type: "inbound_email_action",
    group: "server",
    sdkApi: "InboundEmailAction",
    sdkSince: null,
    table: "sysevent_in_email_action",
    nameField: "name",
    activeField: "active",
    scriptFields: ["script"],
    tiers: SEED_TIERS,
    verified: false,
    appliesToField: "table",
    metaFields: ["table", "type", "action", "order", "active"],
    whenFields: ["type", "order", "condition", "stop_processing"],
  },
  {
    ...BASE,
    type: "sla",
    group: "server",
    sdkApi: "Sla",
    sdkSince: "4.3",
    table: "contract_sla",
    nameField: "name",
    activeField: "active",
    scriptFields: [],
    refFields: [
      { field: "schedule", table: "cmn_schedule", type: "schedule" },
      { field: "workflow", table: "wf_workflow", type: "workflow" },
      { field: "flow", table: "sys_hub_flow", type: "flow" },
    ],
    tiers: SEED_TIERS,
    verified: false,
    appliesToField: "collection",
    metaFields: ["collection", "type", "duration", "active"],
    whenFields: [
      "start_condition",
      "pause_condition",
      "stop_condition",
      "reset_condition",
      "cancel_condition",
      "duration",
    ],
  },
  // Classic UI
  {
    ...BASE,
    type: "data_policy",
    group: "classic-ui",
    sdkApi: "DataPolicy",
    sdkSince: "4.7",
    table: "sys_data_policy2",
    children: [
      {
        table: "sys_data_policy_rule",
        parentField: "sys_data_policy",
        nameField: "field",
        writeFields: ["table", "mandatory", "disabled"],
      },
    ],
    nameField: "short_description",
    activeField: "active",
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
    appliesToField: "model_table",
    metaFields: [
      "model_table",
      "apply_import_set",
      "apply_soap",
      "use_as_ui_policy",
      "active",
    ],
    whenFields: ["conditions", "reverse_if_false", "inherit"],
    writeFields: ["description"],
  },
  {
    ...BASE,
    type: "workspace_form_action",
    group: "classic-ui",
    sdkApi: "UiAction",
    sdkSince: "4.0",
    table: "sys_ux_form_action",
    nameField: "label",
    activeField: "active",
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
    appliesToField: "table",
    metaFields: ["table", "action_name", "order", "active"],
  },
  {
    ...BASE,
    type: "form",
    group: "classic-ui",
    sdkApi: "Form",
    sdkSince: "4.6",
    table: "sys_ui_form",
    // Form → form sections (ordered) → the elements of each section, linked
    // by the section's sys_id held in `sys_ui_form_section.sys_ui_section`.
    children: [
      {
        table: "sys_ui_form_section",
        parentField: "sys_ui_form",
        orderField: "position",
        refFields: [
          {
            field: "sys_ui_section",
            table: "sys_ui_section",
            type: "ui_section",
          },
        ],
      },
      {
        table: "sys_ui_element",
        parentField: "sys_ui_section",
        parentTable: "sys_ui_form_section",
        parentKey: "sys_ui_section",
        orderField: "position",
        nameField: "element",
      },
    ],
    nameField: "name",
    keyFields: ["name", "view"],
    scriptFields: [],
    refFields: [{ field: "view", table: "sys_ui_view", type: "ui_view" }],
    tiers: SEED_TIERS,
    verified: false,
    appliesToField: "name",
    metaFields: ["name", "view"],
  },
  {
    ...BASE,
    type: "ui_section",
    group: "classic-ui",
    sdkApi: "Form",
    sdkSince: "4.6",
    table: "sys_ui_section",
    children: [
      {
        table: "sys_ui_element",
        parentField: "sys_ui_section",
        orderField: "position",
        nameField: "element",
      },
    ],
    nameField: "name",
    scriptFields: [],
    refFields: [{ field: "view", table: "sys_ui_view", type: "ui_view" }],
    tiers: SEED_TIERS,
    verified: false,
    appliesToField: "name",
    metaFields: ["name", "view", "caption"],
  },
  {
    ...BASE,
    type: "list",
    group: "classic-ui",
    sdkApi: "List",
    sdkSince: null,
    table: "sys_ui_list",
    children: [
      {
        table: "sys_ui_list_element",
        parentField: "list_id",
        orderField: "position",
        nameField: "element",
      },
    ],
    nameField: "name",
    scriptFields: [],
    refFields: [{ field: "view", table: "sys_ui_view", type: "ui_view" }],
    tiers: SEED_TIERS,
    verified: false,
    appliesToField: "name",
    metaFields: ["name", "view", "parent", "relationship"],
  },
  {
    ...BASE,
    type: "application_menu",
    group: "classic-ui",
    sdkApi: "ApplicationMenu",
    sdkSince: null,
    table: "sys_app_application",
    children: [
      {
        table: "sys_app_module",
        parentField: "application",
        orderField: "order",
        nameField: "title",
      },
    ],
    nameField: "title",
    activeField: "active",
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
    metaFields: ["category", "order", "roles", "active"],
  },
  {
    ...BASE,
    type: "ui_view",
    group: "classic-ui",
    sdkApi: "Record",
    sdkSince: null,
    table: "sys_ui_view",
    children: [
      {
        table: "sysrule_view",
        parentField: "view",
        nameField: "name",
        scriptFields: ["script"],
      },
    ],
    nameField: "name",
    keyFields: ["name"],
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
    metaFields: ["title"],
  },
  {
    ...BASE,
    type: "list_control",
    group: "classic-ui",
    sdkApi: "Record",
    sdkSince: null,
    table: "sys_ui_list_control",
    nameField: "name",
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
    appliesToField: "name",
    metaFields: ["name", "related_list", "omit_new_button", "omit_edit_button"],
  },
  // Next Experience (SDK APIs; P-9, SDK-PARITY §4.4)
  {
    ...BASE,
    type: "workspace",
    group: "next-experience",
    sdkApi: "Workspace",
    sdkSince: "4.3",
    table: "sys_ux_page_registry",
    children: [
      {
        table: "sys_ux_page_property",
        parentField: "page",
        nameField: "name",
        jsonFields: [{ field: "value", decoder: "json", writable: false }],
      },
    ],
    nameField: "title",
    keyFields: ["path"],
    refFields: [
      {
        field: "root_macroponent",
        table: "sys_ux_macroponent",
        type: "uib_macroponent",
      },
      {
        field: "admin_panel",
        table: "sys_ux_app_config",
        type: "uib_app_config",
      },
    ],
    scriptFields: [],
    tiers: READ_TIER,
    verified: false,
  },
  {
    ...BASE,
    type: "dashboard",
    group: "next-experience",
    sdkApi: "Dashboard",
    sdkSince: null,
    table: "par_dashboard",
    children: [
      {
        table: "par_dashboard_tab",
        parentField: "dashboard",
        orderField: "order",
        nameField: "name",
      },
      {
        table: "par_dashboard_widget",
        parentField: "tab",
        parentTable: "par_dashboard_tab",
      },
      { table: "par_dashboard_permission", parentField: "dashboard" },
    ],
    nameField: "name",
    activeField: "active",
    scriptFields: [],
    tiers: READ_TIER,
    verified: false,
  },
  {
    ...BASE,
    type: "ux_list_menu_config",
    group: "next-experience",
    sdkApi: "UxListMenuConfig",
    sdkSince: null,
    table: "sys_ux_list_menu_config",
    children: [
      {
        table: "sys_ux_list_category",
        parentField: "configuration",
        orderField: "order",
        nameField: "title",
      },
      {
        table: "sys_ux_list",
        parentField: "category",
        parentTable: "sys_ux_list_category",
        orderField: "order",
        nameField: "title",
      },
    ],
    nameField: "name",
    activeField: "active",
    scriptFields: [],
    tiers: READ_TIER,
    verified: false,
  },
  {
    ...BASE,
    type: "ux_applicability",
    group: "next-experience",
    sdkApi: "Applicability",
    sdkSince: null,
    table: "sys_ux_applicability",
    children: [
      { table: "sys_ux_applicability_m2m_list", parentField: "applicability" },
    ],
    nameField: "name",
    activeField: "active",
    scriptFields: [],
    tiers: READ_TIER,
    verified: false,
  },
];
