/** Flow Designer, workflow, catalog, quality, AI, application and reporting rows, then the SDK-next rows. Part of ARTIFACT_TYPES, in registry order. */

import {
  AI_AGENTS_APP,
  type ArtifactType,
  BASE,
  CATALOG_ITEM_CHILDREN,
  CATALOG_POLICY_ACTIONS,
  FLOW_CHILDREN,
  PERFORMANCE_ANALYTICS,
  READ_TIER,
  SCAN_CHECKS,
  SEED_TIERS,
  VARIABLE_CHOICES,
  VARIABLE_WRITE_FIELDS,
  catalogLogic,
} from "./registry-model.js";

export const PROCESS_ROWS: readonly ArtifactType[] = [
  // Flow Designer / Workflow Studio (SDK-PARITY §4.7). Trigger, action and
  // logic instances, flow I/O, variables and stages (FLW-4…8) are children of
  // the flow / subflow they belong to.
  {
    ...BASE,
    type: "flow",
    group: "flow",
    sdkApi: "Flow",
    sdkSince: "4.3",
    table: "sys_hub_flow",
    children: FLOW_CHILDREN,
    nameField: "name",
    keyFields: ["internal_name"],
    activeField: "active",
    scriptFields: [],
    jsonFields: [{ field: "label_cache", decoder: "json", writable: false }],
    refFields: [
      { field: "latest_snapshot", table: "sys_hub_flow_snapshot" },
      { field: "master_snapshot", table: "sys_hub_flow_snapshot" },
    ],
    tiers: READ_TIER,
    verified: false,
  },
  {
    ...BASE,
    type: "subflow",
    group: "flow",
    sdkApi: "Subflow",
    sdkSince: null,
    table: "sys_hub_flow",
    // Subflows share sys_hub_flow with flows; `flow` lists both.
    baseQuery: "type=subflow",
    children: FLOW_CHILDREN,
    nameField: "name",
    keyFields: ["internal_name"],
    activeField: "active",
    scriptFields: [],
    jsonFields: [{ field: "label_cache", decoder: "json", writable: false }],
    refFields: [
      { field: "latest_snapshot", table: "sys_hub_flow_snapshot" },
      { field: "master_snapshot", table: "sys_hub_flow_snapshot" },
    ],
    tiers: READ_TIER,
    verified: false,
  },
  {
    ...BASE,
    type: "flow_action",
    group: "flow",
    sdkApi: "Action",
    sdkSince: null,
    table: "sys_hub_action_type_definition",
    children: [
      {
        table: "sys_hub_action_input",
        parentField: "model",
        nameField: "name",
      },
      {
        table: "sys_hub_action_output",
        parentField: "model",
        nameField: "name",
      },
      {
        table: "sys_hub_step_instance",
        parentField: "action",
        orderField: "order",
        jsonFields: [
          { field: "values", decoder: "flow-values", writable: false },
        ],
      },
    ],
    nameField: "name",
    keyFields: ["internal_name"],
    activeField: "active",
    scriptFields: [],
    tiers: READ_TIER,
    verified: false,
  },
  {
    ...BASE,
    type: "flow_trigger_definition",
    group: "flow",
    sdkApi: "none",
    sdkSince: null,
    table: "sys_hub_trigger_definition",
    nameField: "name",
    scriptFields: [],
    tiers: READ_TIER,
    verified: false,
  },
  {
    ...BASE,
    type: "flow_context",
    group: "flow",
    sdkApi: "none",
    sdkSince: null,
    // Runtime (FLW-9): read only, never snapshotted or written.
    table: "sys_flow_context",
    children: [
      {
        table: "sys_flow_log",
        parentField: "context",
        orderField: "sys_created_on",
      },
    ],
    nameField: "name",
    scriptFields: [],
    refFields: [{ field: "flow", table: "sys_hub_flow", type: "flow" }],
    tiers: READ_TIER,
    verified: false,
  },
  {
    ...BASE,
    type: "playbook",
    group: "flow",
    sdkApi: "PlaybookDefinition",
    sdkSince: null,
    table: "sys_pd_process_definition",
    children: [
      {
        table: "sys_pd_lane",
        parentField: "process_definition",
        orderField: "order",
        nameField: "label",
      },
      {
        table: "sys_pd_activity",
        parentField: "lane",
        parentTable: "sys_pd_lane",
        orderField: "order",
        nameField: "label",
      },
      { table: "sys_pd_trigger_instance", parentField: "process_definition" },
      {
        table: "sys_pd_process_input",
        parentField: "model",
        nameField: "name",
      },
      {
        table: "sys_pd_process_output",
        parentField: "model",
        nameField: "name",
      },
    ],
    nameField: "label",
    activeField: "active",
    scriptFields: [],
    tiers: READ_TIER,
    verified: false,
  },
  {
    ...BASE,
    type: "playbook_context",
    group: "flow",
    sdkApi: "none",
    sdkSince: null,
    // Runtime (FLW-11).
    table: "sys_pd_context",
    children: [{ table: "sys_pd_activity_context", parentField: "context" }],
    nameField: "name",
    scriptFields: [],
    refFields: [
      {
        field: "process_definition",
        table: "sys_pd_process_definition",
        type: "playbook",
      },
    ],
    tiers: READ_TIER,
    verified: false,
  },
  {
    ...BASE,
    type: "decision_table",
    group: "flow",
    sdkApi: "Record",
    sdkSince: null,
    table: "sys_decision",
    children: [
      { table: "sys_decision_input", parentField: "model", nameField: "label" },
      {
        table: "sys_decision_question",
        parentField: "decision_table",
        orderField: "order",
      },
    ],
    nameField: "name",
    scriptFields: [],
    // P-11: explained by the `decision-table` enricher (explainers.ts).
    tiers: SEED_TIERS,
    verified: false,
  },
  // Legacy workflow (no SDK API; SDK-PARITY §4.8). Inbound references (WF-6)
  // are the `workflow` refFields of the referring types.
  {
    ...BASE,
    type: "workflow",
    group: "workflow",
    sdkApi: "none",
    sdkSince: null,
    table: "wf_workflow",
    children: [
      { table: "wf_workflow_version", parentField: "workflow" },
      {
        table: "wf_activity",
        parentField: "workflow",
        orderField: "order",
        nameField: "name",
      },
      {
        table: "wf_transition",
        parentField: "from",
        parentTable: "wf_activity",
      },
      {
        table: "wf_condition",
        parentField: "activity",
        parentTable: "wf_activity",
        orderField: "order",
        nameField: "name",
      },
      {
        table: "wf_stage",
        parentField: "workflow_version",
        parentTable: "wf_workflow_version",
        orderField: "order",
        nameField: "name",
      },
    ],
    nameField: "name",
    activeField: "active",
    scriptFields: [],
    tiers: READ_TIER,
    verified: false,
  },
  {
    ...BASE,
    type: "workflow_activity_definition",
    group: "workflow",
    sdkApi: "none",
    sdkSince: null,
    table: "wf_activity_definition",
    nameField: "name",
    scriptFields: [],
    tiers: READ_TIER,
    verified: false,
  },
  {
    ...BASE,
    type: "workflow_context",
    group: "workflow",
    sdkApi: "none",
    sdkSince: null,
    // Runtime (WF-5).
    table: "wf_context",
    children: [
      { table: "wf_executing", parentField: "context" },
      {
        table: "wf_history",
        parentField: "context",
        orderField: "sys_created_on",
      },
      { table: "wf_log", parentField: "context", orderField: "sys_created_on" },
    ],
    nameField: "name",
    scriptFields: [],
    refFields: [{ field: "workflow", table: "wf_workflow", type: "workflow" }],
    tiers: READ_TIER,
    verified: false,
  },
  // -- P-8: catalog, quality, AI and application rows (SDK-PARITY §4.9 –
  // §4.12). Definition records, not the `sn_sc` consumer view; all unverified
  // until O-5. The AI rows live in licensed store apps (O-9, `licensed`).
  // Service Catalog
  {
    ...BASE,
    type: "catalog_item",
    group: "catalog",
    sdkApi: "CatalogItem",
    sdkSince: "4.3",
    table: "sc_cat_item",
    children: CATALOG_ITEM_CHILDREN,
    nameField: "name",
    activeField: "active",
    scriptFields: [],
    refFields: [{ field: "workflow", table: "wf_workflow", type: "workflow" }],
    tiers: SEED_TIERS,
    verified: false,
    metaFields: ["sys_class_name", "category", "sc_catalogs", "order"],
    // P-24 (CAT-1, U until O-5).
    writeFields: ["short_description", "description"],
  },
  {
    ...BASE,
    type: "record_producer",
    group: "catalog",
    sdkApi: "CatalogItemRecordProducer",
    sdkSince: null,
    // Extends sc_cat_item: the same variables, sets, scripts and policies.
    table: "sc_cat_item_producer",
    children: CATALOG_ITEM_CHILDREN,
    nameField: "name",
    activeField: "active",
    scriptFields: ["script"],
    tiers: SEED_TIERS,
    verified: false,
    appliesToField: "table_name",
    metaFields: ["table_name", "category", "sc_catalogs", "order"],
    writeFields: ["short_description", "description"],
  },
  {
    ...BASE,
    type: "variable_set",
    group: "catalog",
    sdkApi: "VariableSet",
    sdkSince: null,
    table: "item_option_new_set",
    children: [
      {
        table: "item_option_new",
        parentField: "variable_set",
        orderField: "order",
        nameField: "name",
        writeFields: VARIABLE_WRITE_FIELDS,
      },
      ...VARIABLE_CHOICES,
      ...catalogLogic("variable_set", "variable_set"),
      CATALOG_POLICY_ACTIONS,
      // Where the set is used.
      {
        table: "io_set_item",
        parentField: "variable_set",
        orderField: "order",
        refFields: [
          { field: "sc_cat_item", table: "sc_cat_item", type: "catalog_item" },
        ],
      },
    ],
    nameField: "title",
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
    metaFields: ["internal_name", "type", "order"],
    // P-24 (CAT-2, U until O-5).
    writeFields: ["description"],
  },
  {
    ...BASE,
    type: "catalog_variable",
    group: "catalog",
    // Variables are modelled inside CatalogItem / VariableSet, not on their own.
    sdkApi: "none",
    sdkSince: null,
    table: "item_option_new",
    children: [
      {
        table: "question_choice",
        parentField: "question",
        orderField: "order",
        nameField: "text",
        writeFields: ["value"],
      },
    ],
    nameField: "name",
    activeField: "active",
    scriptFields: [],
    refFields: [
      { field: "cat_item", table: "sc_cat_item", type: "catalog_item" },
      {
        field: "variable_set",
        table: "item_option_new_set",
        type: "variable_set",
      },
    ],
    tiers: SEED_TIERS,
    verified: false,
    metaFields: [
      "question_text",
      "type",
      "order",
      "mandatory",
      "cat_item",
      "variable_set",
    ],
    writeFields: ["default_value", "help_text", "reference"],
  },
  {
    ...BASE,
    type: "catalog_ui_policy",
    group: "catalog",
    sdkApi: "CatalogUiPolicy",
    sdkSince: null,
    table: "catalog_ui_policy",
    children: [
      {
        table: "catalog_ui_policy_action",
        parentField: "ui_policy",
        nameField: "catalog_variable",
        writeFields: ["visible", "mandatory", "disabled"],
      },
    ],
    nameField: "short_description",
    activeField: "active",
    scriptFields: ["script_true", "script_false"],
    clientFields: ["script_true", "script_false"],
    refFields: [
      { field: "catalog_item", table: "sc_cat_item", type: "catalog_item" },
      {
        field: "variable_set",
        table: "item_option_new_set",
        type: "variable_set",
      },
    ],
    tiers: SEED_TIERS,
    verified: false,
    metaFields: ["applies_to", "catalog_item", "variable_set", "order"],
    whenFields: ["catalog_conditions", "on_load", "reverse_if_false"],
  },
  // Testing, quality and assessment
  {
    ...BASE,
    type: "atf_test",
    group: "quality",
    sdkApi: "Test",
    sdkSince: null,
    table: "sys_atf_test",
    children: [
      {
        table: "sys_atf_step",
        parentField: "test",
        orderField: "order",
        nameField: "step_config",
      },
    ],
    nameField: "name",
    activeField: "active",
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
    metaFields: ["description", "active"],
  },
  {
    ...BASE,
    type: "atf_test_suite",
    group: "quality",
    sdkApi: "TestSuite",
    sdkSince: null,
    table: "sys_atf_test_suite",
    children: [
      {
        table: "sys_atf_test_suite_test",
        parentField: "test_suite",
        orderField: "order",
        nameField: "test",
        refFields: [{ field: "test", table: "sys_atf_test", type: "atf_test" }],
      },
    ],
    nameField: "name",
    activeField: "active",
    scriptFields: [],
    refFields: [
      { field: "parent", table: "sys_atf_test_suite", type: "atf_test_suite" },
    ],
    tiers: SEED_TIERS,
    verified: false,
    metaFields: ["parent", "active"],
  },
  ...SCAN_CHECKS.map(
    ([type, table, sdkApi, meta]): ArtifactType => ({
      ...BASE,
      type,
      group: "quality",
      sdkApi,
      sdkSince: null,
      table,
      nameField: "name",
      activeField: "active",
      scriptFields: ["script"],
      tiers: SEED_TIERS,
      verified: false,
      metaFields: ["category", "priority", "short_description", ...meta],
    }),
  ),
  {
    ...BASE,
    type: "assessment",
    group: "quality",
    sdkApi: "Assessment",
    sdkSince: null,
    table: "asmt_metric_type",
    children: [
      {
        table: "asmt_metric_category",
        parentField: "metric_type",
        nameField: "name",
      },
      {
        table: "asmt_metric",
        parentField: "metric_type",
        orderField: "order",
        nameField: "name",
      },
      {
        table: "asmt_metric_definition",
        parentField: "metric",
        parentTable: "asmt_metric",
        orderField: "order",
        nameField: "display",
      },
    ],
    nameField: "name",
    activeField: "active",
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
    appliesToField: "table",
    metaFields: ["table", "condition", "active"],
  },
  {
    ...BASE,
    type: "risk_assessment",
    group: "quality",
    sdkApi: "RiskAssessment",
    sdkSince: null,
    table: "change_risk_asmt",
    children: [
      {
        table: "change_risk_asmt_threshold",
        parentField: "risk_assessment",
        orderField: "order",
      },
    ],
    nameField: "name",
    activeField: "active",
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
    metaFields: ["condition", "active"],
  },
  // AI (licensed store apps: absent tables answer available:false)
  {
    ...BASE,
    type: "ai_agent",
    group: "ai",
    sdkApi: "AiAgent",
    sdkSince: null,
    table: "sn_aia_agent",
    children: [
      { table: "sn_aia_agent_config", parentField: "agent" },
      { table: "sn_aia_agent_tool_m2m", parentField: "agent" },
      {
        table: "sn_aia_tool",
        parentField: "sys_id",
        parentTable: "sn_aia_agent_tool_m2m",
        parentKey: "tool",
        nameField: "name",
      },
      { table: "sn_aia_trigger_configuration", parentField: "agent" },
      { table: "sn_aia_version", parentField: "agent" },
    ],
    nameField: "name",
    activeField: "active",
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
    licensed: AI_AGENTS_APP,
    metaFields: ["description", "active"],
  },
  {
    ...BASE,
    type: "ai_agentic_workflow",
    group: "ai",
    sdkApi: "AiAgenticWorkflow",
    sdkSince: null,
    table: "sn_aia_usecase",
    children: [
      {
        table: "sn_aia_team",
        parentField: "sys_id",
        parentKey: "team",
        nameField: "name",
      },
      {
        table: "sn_aia_team_member",
        parentField: "team",
        parentTable: "sn_aia_team",
        refFields: [
          { field: "agent", table: "sn_aia_agent", type: "ai_agent" },
        ],
      },
    ],
    nameField: "name",
    activeField: "active",
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
    licensed: AI_AGENTS_APP,
    metaFields: ["description", "team", "active"],
  },
  {
    ...BASE,
    type: "now_assist_skill",
    group: "ai",
    sdkApi: "NowAssistSkillConfig",
    sdkSince: null,
    // The inventory lists the family as `sn_nowassist_skill_*` (U).
    table: "sn_nowassist_skill_config",
    nameField: "name",
    activeField: "active",
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
    licensed: "Now Assist Skill Kit (sn_nowassist_skill)",
  },
  // Application, scope and delivery
  {
    ...BASE,
    type: "application",
    group: "application",
    // now.config.json, not a Fluent API.
    sdkApi: "none",
    sdkSince: null,
    table: "sys_app",
    children: [
      {
        table: "sys_scope_dependency",
        parentField: "scope",
        nameField: "dependency",
      },
      {
        table: "sys_package_dependency",
        parentField: "sys_package",
        nameField: "dependency",
      },
    ],
    nameField: "name",
    keyFields: ["scope"],
    activeField: "active",
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
    metaFields: ["scope", "version", "vendor", "active"],
  },
  {
    ...BASE,
    type: "app_dependency",
    group: "application",
    sdkApi: "none",
    sdkSince: null,
    table: "sys_scope_dependency",
    nameField: "dependency",
    scopeField: "scope",
    scriptFields: [],
    refFields: [
      { field: "scope", table: "sys_app", type: "application" },
      { field: "dependency", table: "sys_app", type: "application" },
    ],
    tiers: SEED_TIERS,
    verified: false,
    metaFields: ["scope", "dependency", "min_version"],
  },
  {
    ...BASE,
    type: "customer_update",
    group: "application",
    sdkApi: "none",
    sdkSince: null,
    // The payload is XML, not JSON: explain shows it capped, undecoded.
    table: "sys_update_xml",
    nameField: "name",
    scopeField: "application",
    scriptFields: [],
    tiers: READ_TIER,
    verified: false,
    metaFields: ["type", "target_name", "action", "update_set", "update_guid"],
  },
  {
    ...BASE,
    type: "source_control",
    group: "application",
    sdkApi: "none",
    sdkSince: null,
    table: "sys_repo_config",
    nameField: "url",
    scriptFields: [],
    tiers: READ_TIER,
    verified: false,
    metaFields: ["url", "branch", "application"],
  },
  // -- N-8: reports and Performance Analytics (SDK-PARITY §4.13) -----------
  // Read-only seeds. O-5: verify on a live instance — every table and field
  // below comes from the SDK table schemas (`sys_report`, `pa_dashboards`) or
  // the platform documentation (the other `pa_*` tables) and is unverified.
  {
    ...BASE,
    type: "report",
    group: "reporting",
    // The Fluent `Record()` fallback only; no report API on the baseline.
    sdkApi: "none",
    sdkSince: null,
    // O-5: verify on a live instance (sys_report, sys_report_users_groups).
    table: "sys_report",
    children: [
      {
        table: "sys_report_users_groups",
        parentField: "report_id",
        refFields: [
          { field: "user_id", table: "sys_user" },
          { field: "group_id", table: "sys_user_group" },
        ],
      },
    ],
    nameField: "title",
    scriptFields: [],
    // O-5: verify on a live instance.
    refFields: [
      {
        field: "report_source",
        table: "sys_report_source",
        type: "report_source",
      },
      { field: "report_drilldown", table: "sys_report_drill" },
      { field: "list_ui_view", table: "sys_ui_view" },
      { field: "group", table: "sys_user_group" },
    ],
    tiers: SEED_TIERS,
    verified: false,
    appliesToField: "table",
    // O-5: verify on a live instance (`type` is not in the SDK schema).
    metaFields: [
      "table",
      "type",
      "field",
      "aggregate",
      "filter",
      "field_list",
      "is_published",
      "roles",
    ],
  },
  {
    ...BASE,
    type: "report_source",
    group: "reporting",
    sdkApi: "none",
    sdkSince: null,
    // O-5: verify on a live instance.
    table: "sys_report_source",
    nameField: "name",
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
    appliesToField: "table",
    metaFields: ["table", "filter"],
  },
  {
    ...BASE,
    type: "pa_indicator",
    group: "reporting",
    sdkApi: "none",
    sdkSince: null,
    // O-5: verify on a live instance (pa_indicators, pa_indicator_breakdowns).
    table: "pa_indicators",
    children: [
      {
        table: "pa_indicator_breakdowns",
        parentField: "indicator",
        refFields: [
          { field: "breakdown", table: "pa_breakdowns", type: "pa_breakdown" },
        ],
      },
    ],
    nameField: "name",
    activeField: "active",
    scriptFields: [],
    // O-5: verify on a live instance.
    refFields: [
      { field: "cube", table: "pa_cubes", type: "pa_indicator_source" },
      { field: "script", table: "pa_scripts", type: "pa_script" },
    ],
    tiers: SEED_TIERS,
    verified: false,
    licensed: PERFORMANCE_ANALYTICS,
    metaFields: [
      "type",
      "cube",
      "aggregate",
      "field",
      "conditions",
      "frequency",
      "formula",
      "active",
    ],
  },
  {
    ...BASE,
    type: "pa_indicator_source",
    group: "reporting",
    sdkApi: "none",
    sdkSince: null,
    // O-5: verify on a live instance.
    table: "pa_cubes",
    nameField: "name",
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
    licensed: PERFORMANCE_ANALYTICS,
    appliesToField: "facts_table",
    metaFields: ["facts_table", "conditions", "frequency"],
  },
  {
    ...BASE,
    type: "pa_breakdown",
    group: "reporting",
    sdkApi: "none",
    sdkSince: null,
    // O-5: verify on a live instance (pa_breakdowns, pa_breakdown_mappings).
    table: "pa_breakdowns",
    children: [
      {
        table: "pa_breakdown_mappings",
        parentField: "breakdown",
        refFields: [
          { field: "script", table: "pa_scripts", type: "pa_script" },
        ],
      },
    ],
    nameField: "name",
    activeField: "active",
    scriptFields: [],
    // O-5: verify on a live instance.
    refFields: [{ field: "dimension", table: "pa_dimensions" }],
    tiers: SEED_TIERS,
    verified: false,
    licensed: PERFORMANCE_ANALYTICS,
    metaFields: ["dimension", "active"],
  },
  {
    ...BASE,
    type: "pa_script",
    group: "reporting",
    sdkApi: "none",
    sdkSince: null,
    // O-5: verify on a live instance. A script field, but not a script-tools
    // type: list_scripts / search_code do not sweep it (no enum growth).
    table: "pa_scripts",
    nameField: "name",
    scriptFields: ["script"],
    tiers: SEED_TIERS,
    verified: false,
    licensed: PERFORMANCE_ANALYTICS,
    appliesToField: "facts_table",
    metaFields: ["facts_table", "fields"],
  },
  {
    ...BASE,
    type: "pa_dashboard",
    group: "reporting",
    sdkApi: "none",
    sdkSince: null,
    // O-5: verify on a live instance (pa_m2m_dashboard_tabs, pa_tabs).
    table: "pa_dashboards",
    children: [
      {
        table: "pa_m2m_dashboard_tabs",
        parentField: "dashboard",
        orderField: "order",
      },
      {
        table: "pa_tabs",
        parentField: "sys_id",
        parentTable: "pa_m2m_dashboard_tabs",
        parentKey: "tab",
        nameField: "name",
      },
    ],
    nameField: "name",
    activeField: "active",
    scriptFields: [],
    // From the SDK `pa_dashboards` schema; O-5: verify on a live instance.
    refFields: [
      {
        field: "experience_dashboard",
        table: "par_dashboard",
        type: "dashboard",
      },
      {
        field: "managed_breakdown",
        table: "pa_breakdowns",
        type: "pa_breakdown",
      },
      { field: "breakdown_source", table: "pa_dimensions" },
      { field: "group", table: "pa_dashboards_group" },
      { field: "owner", table: "sys_user" },
    ],
    tiers: SEED_TIERS,
    verified: false,
    licensed: PERFORMANCE_ANALYTICS,
    metaFields: ["description", "group", "owner", "active"],
  },
  // -- SDK 4.13 (on npm `latest` since the 4.13.6 re-pin; SDK-PARITY CORE-3) --
  // The tables are unverified until O-5.
  {
    ...BASE,
    type: "database_view",
    group: "core",
    sdkApi: "DatabaseView",
    sdkSince: "4.13.0",
    table: "sys_db_view",
    children: [
      { table: "sys_db_view_table", parentField: "view", orderField: "order" },
    ],
    nameField: "name",
    scriptFields: [],
    tiers: SEED_TIERS,
    verified: false,
  },
];
