// Generated by scripts/gen-fluent-actions.mjs from @servicenow/sdk 4.12.2
// (sdk-core built-ins/actions/core, action-steps and fluent/tables). Do not edit; regenerate
// after an SDK bump.

/** One action.core input: its column kind (`<kind>Column`) and flags. */
export interface CoreActionInput {
  kind: string;
  /** Visible and mandatory: a typed call must pass it. */
  mandatory?: true;
  /** visible / visible_in_fd false: not part of the typed inputs. */
  hidden?: true;
}

/** One action.core action: its sys_id (the untyped `wfa.action()` form), name and inputs. */
export interface CoreActionSpec {
  sysId: string;
  name: string;
  inputs: Readonly<Record<string, CoreActionInput>>;
}

/** The SDK version the table was generated from. */
export const SDK_ACTIONS_VERSION = "4.12.2";

/** `action.core.*` by export name. */
export const SDK_CORE_ACTIONS: Readonly<Record<string, CoreActionSpec>> = {
  addWorknoteLinkToContext: {
    sysId: "fd4a0fb70f003300ecf0cc52ff767e2a",
    name: "Add Worknote Link to Context",
    inputs: {
      journal_field: {
        kind: "FieldName",
        mandatory: true,
      },
      record: {
        kind: "DocumentId",
        mandatory: true,
      },
      table: {
        kind: "TableName",
        mandatory: true,
      },
      additional_comments: {
        kind: "String",
      },
    },
  },
  askForApproval: {
    sysId: "f8f2e9920b10030085c083eb37673abd",
    name: "Ask For Approval",
    inputs: {
      approval_field: {
        kind: "FieldName",
      },
      journal_field: {
        kind: "FieldName",
      },
      due_date: {
        kind: "ScheduleDateTime",
      },
      approval_conditions: {
        kind: "ApprovalRules",
        mandatory: true,
      },
      table: {
        kind: "TableName",
      },
      record: {
        kind: "DocumentId",
        mandatory: true,
      },
      approval_reason: {
        kind: "String",
      },
    },
  },
  associateRecordToEmail: {
    sysId: "7b95a4c0a73133008299b39f087901b4",
    name: "Associate Record to Email",
    inputs: {
      target_record: {
        kind: "DocumentId",
        mandatory: true,
      },
      email_record: {
        kind: "DocumentId",
        mandatory: true,
      },
    },
  },
  copyAttachment: {
    sysId: "30fe6cdb0f973300dfd3694e68767e5a",
    name: "Copy Attachment",
    inputs: {
      target_record: {
        kind: "DocumentId",
        mandatory: true,
      },
      attachment_record: {
        kind: "Reference",
        mandatory: true,
      },
      table: {
        kind: "TableName",
        mandatory: true,
      },
    },
  },
  createCatalogTask: {
    sysId: "af51fd0e73141300612c273ffff6a785",
    name: "Create Catalog Task",
    inputs: {
      ah_wait: {
        kind: "Boolean",
      },
      ah_fields: {
        kind: "TemplateValue",
      },
      catalog_variables: {
        kind: "SlushBucket",
      },
      ah_short_description: {
        kind: "String",
      },
      ah_table_name: {
        kind: "TableName",
      },
      template_catalog_item: {
        kind: "Reference",
      },
      ah_requested_item: {
        kind: "Reference",
        mandatory: true,
      },
    },
  },
  createOrUpdateRecord: {
    sysId: "ab575ae253b3230034c6ddeeff7b12f1",
    name: "Create or Update Record",
    inputs: {
      fields: {
        kind: "TemplateValue",
        mandatory: true,
      },
      table_name: {
        kind: "TableName",
        mandatory: true,
      },
    },
  },
  createRecord: {
    sysId: "2de05916c31332002841b63b12d3aee1",
    name: "Create Record",
    inputs: {
      table_name: {
        kind: "TableName",
        mandatory: true,
      },
      values: {
        kind: "TemplateValue",
        mandatory: true,
      },
    },
  },
  createTask: {
    sysId: "2b3a6335531003003bf1d9109ec58759",
    name: "Create Task",
    inputs: {
      task_table: {
        kind: "TableName",
        mandatory: true,
      },
      wait: {
        kind: "Boolean",
      },
      field_values: {
        kind: "TemplateValue",
      },
    },
  },
  deleteAttachment: {
    sysId: "bdc2a0170f973300dfd3694e68767e47",
    name: "Delete Attachment",
    inputs: {
      delete_all_: {
        kind: "Boolean",
      },
      attachment_file_name: {
        kind: "String",
      },
      record: {
        kind: "DocumentId",
        mandatory: true,
      },
      table: {
        kind: "TableName",
        mandatory: true,
      },
    },
  },
  deleteRecord: {
    sysId: "c3e09916c31332002841b63b12d3aedf",
    name: "Delete Record",
    inputs: {
      record: {
        kind: "DocumentId",
        mandatory: true,
      },
    },
  },
  fireEvent: {
    sysId: "80a30edeff30311077a95dac793bf19b",
    name: "Fire Event",
    inputs: {
      parm1: {
        kind: "String",
      },
      table: {
        kind: "TableName",
      },
      record: {
        kind: "DocumentId",
        mandatory: true,
      },
      parm2: {
        kind: "String",
      },
      event_name: {
        kind: "Reference",
        mandatory: true,
      },
    },
  },
  getAttachmentsOnRecord: {
    sysId: "082e70db0f4273003788001ea8767e02",
    name: "Get Attachments on Record",
    inputs: {
      file_name: {
        kind: "String",
      },
      source_record: {
        kind: "DocumentId",
        mandatory: true,
      },
    },
  },
  getCatalogVariables: {
    sysId: "330ba3abc31013002841b63b12d3aee8",
    name: "Get Catalog Variables",
    inputs: {
      catalog_variables: {
        kind: "SlushBucket",
      },
      requested_item: {
        kind: "Reference",
        mandatory: true,
      },
      template_catalog_item: {
        kind: "Reference",
        mandatory: true,
      },
    },
  },
  getEmailHeader: {
    sysId: "a8cfa3efa70223008299b39f0879018b",
    name: "Get Email Header",
    inputs: {
      target_header: {
        kind: "String",
        mandatory: true,
      },
      email_record: {
        kind: "Reference",
        mandatory: true,
      },
    },
  },
  getLatestResponseTextFromEmail: {
    sysId: "a159d7820f13101051218e8ebc767eea",
    name: "Get Latest Response Text From Email",
    inputs: {
      email_record: {
        kind: "Reference",
        mandatory: true,
      },
    },
  },
  log: {
    sysId: "5bc1bcc6531003003bf1d9109ec587d4",
    name: "Log",
    inputs: {
      log_level: {
        kind: "Choice",
      },
      log_message: {
        kind: "String",
      },
    },
  },
  lookUpEmailAttachments: {
    sysId: "2dbeaf29c7322300f4eba1425a976340",
    name: "Look Up Email Attachments",
    inputs: {
      email_record: {
        kind: "Reference",
        mandatory: true,
      },
    },
  },
  lookUpRecord: {
    sysId: "9d09f99587003300663ca1bb36cb0ba3",
    name: "Look Up Record",
    inputs: {
      sort_type: {
        kind: "Choice",
      },
      conditions: {
        kind: "Conditions",
      },
      dont_fail_flow_on_error: {
        kind: "Boolean",
      },
      table: {
        kind: "TableName",
      },
      sort_column: {
        kind: "FieldName",
      },
      if_multiple_records_are_found_action: {
        kind: "Choice",
      },
    },
  },
  lookUpRecords: {
    sysId: "43400a1587003300663ca1bb36cb0b4b",
    name: "Look Up Records",
    inputs: {
      conditions: {
        kind: "Conditions",
      },
      table: {
        kind: "TableName",
      },
      sort_type: {
        kind: "Choice",
      },
      sort_column: {
        kind: "FieldName",
      },
      max_results: {
        kind: "Integer",
      },
    },
  },
  lookupAttachment: {
    sysId: "6ecdee36935023005e69925cf67ffb47",
    name: "Look Up Attachment",
    inputs: {
      file_name: {
        kind: "String",
      },
      source_record: {
        kind: "DocumentId",
        mandatory: true,
      },
    },
  },
  moveAttachment: {
    sysId: "7159823353cc10103a33ddeeff7b1216",
    name: "Move Attachment",
    inputs: {
      source_attachment_record: {
        kind: "Reference",
        mandatory: true,
      },
      target_record: {
        kind: "DocumentId",
        mandatory: true,
      },
      table: {
        kind: "TableName",
        mandatory: true,
      },
    },
  },
  moveEmailAttachmentsToRecord: {
    sysId: "bd8fcd48a73133008299b39f087901fc",
    name: "Move Email Attachments to Record",
    inputs: {
      target_record: {
        kind: "DocumentId",
        mandatory: true,
      },
      email_record: {
        kind: "DocumentId",
        mandatory: true,
      },
    },
  },
  recordProducer: {
    sysId: "87a397837333001098e194596bf6a7bc",
    name: "Record Producer",
    inputs: {
      record_table: {
        kind: "TableName",
        hidden: true,
      },
      catalog_item: {
        kind: "Reference",
        mandatory: true,
      },
      catalog_item_inputs: {
        kind: "String",
      },
      _snc_dont_fail_on_error: {
        kind: "Boolean",
      },
    },
  },
  sendEmail: {
    sysId: "c1806bf4a70323008299b39f087901cb",
    name: "Send Email",
    inputs: {
      table_name: {
        kind: "TableName",
      },
      ah_cc: {
        kind: "String",
      },
      watermark_email: {
        kind: "Boolean",
      },
      ah_bcc: {
        kind: "String",
      },
      ah_subject: {
        kind: "String",
        mandatory: true,
      },
      ah_body: {
        kind: "Html",
      },
      record: {
        kind: "DocumentId",
      },
      ah_to: {
        kind: "String",
        mandatory: true,
      },
    },
  },
  sendNotification: {
    sysId: "0d8dd9f10f11101051218e8ebc767e27",
    name: "Send Notification",
    inputs: {
      table_name: {
        kind: "TableName",
      },
      record: {
        kind: "DocumentId",
      },
      notification: {
        kind: "Reference",
        mandatory: true,
      },
    },
  },
  sendSms: {
    sysId: "027499be7333001099792f163cf6a7a7",
    name: "Send SMS",
    inputs: {
      recipients: {
        kind: "String",
        mandatory: true,
      },
      message: {
        kind: "String",
        mandatory: true,
      },
    },
  },
  slaPercentageTimer: {
    sysId: "a1a50c4573873300d70877186bf6a762",
    name: "SLA Percentage Timer",
    inputs: {
      percentage: {
        kind: "Integer",
        mandatory: true,
      },
      task_sla_record: {
        kind: "Reference",
        hidden: true,
      },
    },
  },
  submitCatalogItemRequest: {
    sysId: "c7a04c607312001098e194596bf6a72a",
    name: "Submit Catalog Item Request",
    inputs: {
      catalog_item_inputs: {
        kind: "String",
      },
      delivery_address: {
        kind: "String",
      },
      sysparm_requested_for: {
        kind: "Reference",
      },
      schedule: {
        kind: "Reference",
      },
      duration: {
        kind: "Duration",
      },
      _snc_dont_fail_on_error: {
        kind: "Boolean",
      },
      catalog_item: {
        kind: "Reference",
        mandatory: true,
      },
      timeout_flag: {
        kind: "Boolean",
      },
      sysparm_quantity: {
        kind: "Integer",
      },
      special_instructions: {
        kind: "String",
      },
      wait_for_completion: {
        kind: "Boolean",
      },
    },
  },
  updateMultipleRecords: {
    sysId: "9daf2a72c75100105312134c95c26073",
    name: "Update Multiple Records",
    inputs: {
      table_name: {
        kind: "TableName",
        mandatory: true,
      },
      conditions: {
        kind: "Conditions",
        mandatory: true,
      },
      sort_type: {
        kind: "Choice",
      },
      field_values: {
        kind: "TemplateValue",
        mandatory: true,
      },
      sort_column: {
        kind: "FieldName",
      },
      dont_fail_flow_on_error: {
        kind: "Boolean",
      },
    },
  },
  updateRecord: {
    sysId: "f9d01dd2c31332002841b63b12d3aea1",
    name: "Update Record",
    inputs: {
      table_name: {
        kind: "TableName",
        mandatory: true,
      },
      record: {
        kind: "DocumentId",
        mandatory: true,
      },
      values: {
        kind: "TemplateValue",
        mandatory: true,
      },
    },
  },
  waitForCondition: {
    sysId: "89ce8a4187120010663ca1bb36cb0be3",
    name: "Wait For Condition",
    inputs: {
      timeout_duration: {
        kind: "Duration",
      },
      table_name: {
        kind: "TableName",
      },
      timeout_schedule: {
        kind: "Reference",
      },
      timeout_flag: {
        kind: "Boolean",
      },
      record: {
        kind: "DocumentId",
        mandatory: true,
      },
      conditions: {
        kind: "Conditions",
        mandatory: true,
      },
    },
  },
  waitForEmailReply: {
    sysId: "8e38de067f0312108e688c90ac866501",
    name: "Wait For Email Reply",
    inputs: {
      timeout_schedule: {
        kind: "Reference",
      },
      record: {
        kind: "Reference",
        mandatory: true,
      },
      enable_timeout: {
        kind: "Boolean",
      },
      timeout_duration: {
        kind: "Duration",
      },
    },
  },
  waitForMessage: {
    sysId: "605d0ab8931012105cd18166448918db",
    name: "Wait For Message",
    inputs: {
      message: {
        kind: "String",
        mandatory: true,
      },
      enable_timeout: {
        kind: "Boolean",
      },
      timeout: {
        kind: "Duration",
      },
    },
  },
};

/** `actionStep.*` (the steps of an Action() body) by export name. */
export const SDK_ACTION_STEPS: Readonly<Record<string, CoreActionSpec>> = {
  askForApproval: {
    sysId: "a4eb47900b22320085c083eb37673acc",
    name: "Ask for Approval",
    inputs: {
      approval_reason: {
        kind: "String",
      },
      approval_conditions: {
        kind: "Generic",
        mandatory: true,
      },
      record: {
        kind: "DocumentId",
        mandatory: true,
      },
      table: {
        kind: "TableName",
      },
      due_date: {
        kind: "ScheduleDateTime",
      },
      approval_field: {
        kind: "FieldName",
      },
      journal_field: {
        kind: "FieldName",
      },
    },
  },
  collectActivityContext: {
    sysId: "05a6e480a301311029c4d1f3e31e61f1",
    name: "Collect Activity Context",
    inputs: {},
  },
  createAppFromPayload: {
    sysId: "65a40b525b12101083f30f216581c787",
    name: "Create App From Payload",
    inputs: {
      template_instance_id: {
        kind: "String",
        mandatory: true,
      },
      scan_id: {
        kind: "String",
      },
    },
  },
  createOrUpdateRecord: {
    sysId: "8f5c107a53a3230034c6ddeeff7b129d",
    name: "Create or Update Record",
    inputs: {
      fields: {
        kind: "TemplateValue",
      },
      table: {
        kind: "TableName",
      },
    },
  },
  createRecord: {
    sysId: "9cbaa0f267003200553fafb49585ef69",
    name: "Create Record",
    inputs: {
      skip_insert: {
        kind: "Boolean",
      },
      create_record_field_values: {
        kind: "TemplateValue",
      },
      create_record_table_name: {
        kind: "TableName",
      },
    },
  },
  createRecordForRemoteTable: {
    sysId: "e0b9272d53112110aba6ddeeff7b1224",
    name: "Create Record for Remote Table",
    inputs: {
      query_id: {
        kind: "Generic",
        mandatory: true,
      },
      create_record_table_name: {
        kind: "TableName",
      },
      create_record_field_values: {
        kind: "TemplateValue",
      },
    },
  },
  createTask: {
    sysId: "07973e960b233200cbd9e240e0ea604e",
    name: "Create Task",
    inputs: {
      skip_insert: {
        kind: "Boolean",
      },
      create_record_field_values: {
        kind: "TemplateValue",
      },
      create_record_table_name: {
        kind: "TableName",
      },
      wait: {
        kind: "Boolean",
      },
    },
  },
  deleteMultipleRecords: {
    sysId: "8c6b7466c71100105312134c95c2602a",
    name: "Delete Multiple Records",
    inputs: {
      set_workflow: {
        kind: "Boolean",
      },
      table_name: {
        kind: "TableName",
        mandatory: true,
      },
      dont_fail_flow_on_error: {
        kind: "Boolean",
      },
      sort_column: {
        kind: "FieldName",
      },
      conditions: {
        kind: "Conditions",
        mandatory: true,
      },
      sort_type: {
        kind: "Choice",
      },
    },
  },
  deleteRecord: {
    sysId: "b67821c1c723220061f553c6f09763c2",
    name: "Delete Record",
    inputs: {
      record: {
        kind: "DocumentId",
      },
      table_name: {
        kind: "TableName",
      },
    },
  },
  email: {
    sysId: "4c5f36a37f0b32005f58108c3ffa9126",
    name: "Email",
    inputs: {
      watermark_email: {
        kind: "Boolean",
      },
      cc: {
        kind: "String",
      },
      to: {
        kind: "String",
        mandatory: true,
      },
      subject: {
        kind: "String",
        mandatory: true,
      },
      body: {
        kind: "Generic",
      },
      record: {
        kind: "DocumentId",
      },
      table_name: {
        kind: "TableName",
      },
      bcc: {
        kind: "String",
      },
    },
  },
  fireEvent: {
    sysId: "092bb996ff30311077a95dac793bf166",
    name: "Fire Event",
    inputs: {
      table: {
        kind: "TableName",
      },
      parm1: {
        kind: "String",
      },
      parm2: {
        kind: "String",
      },
      event_name: {
        kind: "Reference",
        mandatory: true,
      },
      record: {
        kind: "DocumentId",
        mandatory: true,
      },
    },
  },
  getLatestResponseTextFromEmail: {
    sysId: "0e07df020f13101051218e8ebc767e57",
    name: "Get Latest Response Text From Email",
    inputs: {
      email_record: {
        kind: "Reference",
        mandatory: true,
      },
    },
  },
  log: {
    sysId: "a03fea9bc712220061f553c6f09763b1",
    name: "Log",
    inputs: {
      log_message: {
        kind: "String",
      },
      log_level: {
        kind: "Choice",
      },
    },
  },
  lookUpRecord: {
    sysId: "dc9c26043b23220057a4a2e334efc447",
    name: "Look Up Record",
    inputs: {
      conditions: {
        kind: "Conditions",
      },
      multiple_records_found: {
        kind: "Choice",
      },
      sort_column: {
        kind: "FieldName",
      },
      dont_fail_flow_on_error: {
        kind: "Boolean",
      },
      sort_type: {
        kind: "Choice",
      },
      lookup_table_name: {
        kind: "TableName",
      },
    },
  },
  lookUpRecords: {
    sysId: "48526b2dc32a32002841b63b12d3ae72",
    name: "Look Up Records",
    inputs: {
      limit: {
        kind: "Integer",
      },
      sort_column: {
        kind: "FieldName",
      },
      table_name: {
        kind: "TableName",
      },
      sort_type: {
        kind: "Choice",
      },
      conditions: {
        kind: "Conditions",
      },
    },
  },
  notification: {
    sysId: "5d31f8f37f1322004d145212bdfa9145",
    name: "Notification",
    inputs: {
      record: {
        kind: "DocumentId",
      },
      table_name: {
        kind: "TableName",
      },
      notification: {
        kind: "Reference",
        mandatory: true,
      },
    },
  },
  script: {
    sysId: "106afb6647032200b4fad7527c9a71e7",
    name: "Script",
    inputs: {
      mid_cluster: {
        kind: "DocumentId",
      },
      host: {
        kind: "String",
      },
      connection_alias: {
        kind: "Reference",
      },
      mid_selection_type: {
        kind: "Choice",
      },
      script: {
        kind: "Script",
      },
      required_run_time: {
        kind: "Choice",
        mandatory: true,
      },
      capabilities: {
        kind: "Reference",
      },
      mid_selection: {
        kind: "Choice",
      },
      mid_server: {
        kind: "DocumentId",
      },
      application: {
        kind: "Reference",
      },
    },
  },
  sms: {
    sysId: "f760b5c2737c001086592f163cf6a758",
    name: "SMS",
    inputs: {
      message: {
        kind: "String",
        mandatory: true,
      },
      recipients: {
        kind: "String",
        mandatory: true,
      },
    },
  },
  updateMultipleRecords: {
    sysId: "a3dfc066c7dd00105312134c95c26014",
    name: "Update Multiple Records",
    inputs: {
      set_autosysfields: {
        kind: "Boolean",
      },
      sort_column: {
        kind: "FieldName",
      },
      conditions: {
        kind: "Conditions",
        mandatory: true,
      },
      sort_type: {
        kind: "Choice",
      },
      set_workflow: {
        kind: "Boolean",
      },
      field_values: {
        kind: "TemplateValue",
        mandatory: true,
      },
      table_name: {
        kind: "TableName",
        mandatory: true,
      },
      dont_fail_flow_on_error: {
        kind: "Boolean",
      },
    },
  },
  updateRecord: {
    sysId: "b51f683667003200553fafb49585ef3f",
    name: "Update Record",
    inputs: {
      table_name: {
        kind: "TableName",
        mandatory: true,
      },
      record: {
        kind: "DocumentId",
        mandatory: true,
      },
      update_record_field_values: {
        kind: "TemplateValue",
      },
    },
  },
  waitForCondition: {
    sysId: "4c9234ca0b18030085c083eb37673aaa",
    name: "Wait For Condition",
    inputs: {
      timeout_duration: {
        kind: "Duration",
      },
      table_name: {
        kind: "TableName",
      },
      conditions: {
        kind: "Conditions",
        mandatory: true,
      },
      timeout_schedule: {
        kind: "Reference",
      },
      timeout_flag: {
        kind: "Boolean",
      },
      record: {
        kind: "DocumentId",
        mandatory: true,
      },
    },
  },
  waitForEmailReply: {
    sysId: "81e15fbd7fcb12108e688c90ac866541",
    name: "Wait For Email Reply",
    inputs: {
      record: {
        kind: "Reference",
        mandatory: true,
      },
      timeout_duration: {
        kind: "Duration",
      },
      enable_timeout: {
        kind: "Boolean",
      },
      timeout_schedule: {
        kind: "Reference",
      },
    },
  },
  waitForMessage: {
    sysId: "0d9746f0931012105cd181664489188c",
    name: "Wait For Message",
    inputs: {
      timeout_duration: {
        kind: "Duration",
      },
      message: {
        kind: "Generic",
        mandatory: true,
      },
      enable_timeout: {
        kind: "Boolean",
      },
    },
  },
};

/** Integer / decimal / float columns (inherited included) of the tables the SDK has a schema for: `Record()` data takes a number there. */
export const SDK_NUMERIC_COLUMNS: Readonly<Record<string, readonly string[]>> =
  {
    alm_asset: ["install_status", "quantity", "sys_mod_count"],
    alm_hardware: ["install_status", "quantity", "sys_mod_count"],
    analytics_dashboard: ["sys_mod_count"],
    analytics_visualization: ["sys_mod_count"],
    ast_contract: [
      "average_lead_time",
      "cost_adjustment",
      "cost_adjustment_percentage",
      "discount",
      "license_quantity_entitled",
      "renewal_notice_period",
      "sys_mod_count",
      "tax_rate",
      "termination_notice_days",
      "termination_notice_period",
    ],
    business_calendar: ["sys_mod_count"],
    business_calendar_span: [
      "counter",
      "index0",
      "index1",
      "index2",
      "index3",
      "index4",
      "index5",
      "index6",
      "index7",
      "index8",
      "index9",
    ],
    business_calendar_span_name: ["sys_mod_count"],
    change_request: [
      "escalation",
      "impact",
      "order",
      "priority",
      "reassignment_count",
      "review_status",
      "risk",
      "route_reason",
      "scope",
      "state",
      "sys_mod_count",
      "urgency",
    ],
    cmdb: ["cost", "install_status", "sys_mod_count"],
    cmdb_ci: [
      "attestation_score",
      "cost",
      "fault_count",
      "install_status",
      "operational_status",
      "sys_mod_count",
    ],
    cmdb_ci_business_app: [
      "active_user_count",
      "attestation_score",
      "cost",
      "fault_count",
      "install_status",
      "operational_status",
      "organization_unit_count",
      "sys_mod_count",
    ],
    cmdb_ci_service: [
      "attestation_score",
      "cost",
      "fault_count",
      "install_status",
      "operational_status",
      "sys_mod_count",
    ],
    cmdb_model: [
      "current",
      "depth",
      "eol_emission",
      "expected_lifespan",
      "flow_rate",
      "height",
      "length",
      "manufacturing_emission",
      "power_consumption",
      "rack_units",
      "rated_power",
      "sound_power",
      "sys_mod_count",
      "transportation_emission",
      "typical_energy_consumption",
      "usage_emission",
      "voltage",
      "volume",
      "weight",
      "weight_decimal",
      "width",
    ],
    cmn_building: ["floors", "sys_mod_count"],
    cmn_cost_center: ["sys_mod_count"],
    cmn_department: ["head_count", "sys_mod_count"],
    cmn_location: ["latitude", "longitude", "sys_mod_count"],
    cmn_relative_duration: ["duration_amount", "sys_mod_count"],
    cmn_schedule: ["sys_mod_count"],
    cmn_schedule_span: [
      "counter",
      "index0",
      "index1",
      "index2",
      "index3",
      "index4",
      "index5",
      "index6",
      "index7",
      "index8",
      "index9",
    ],
    contract_sla: ["sys_mod_count"],
    core_company: [
      "discount",
      "latitude",
      "longitude",
      "num_employees",
      "sys_mod_count",
    ],
    dl_definition: ["sys_mod_count"],
    dl_definition_rel_match: ["sys_mod_count"],
    dl_definition_rel_set: ["sys_mod_count"],
    dl_matcher: ["order", "sys_mod_count"],
    email_access_restriction: ["sys_mod_count"],
    incident: [
      "business_stc",
      "calendar_stc",
      "child_incidents",
      "escalation",
      "hold_reason",
      "impact",
      "incident_state",
      "notify",
      "order",
      "priority",
      "reassignment_count",
      "reopen_count",
      "route_reason",
      "severity",
      "state",
      "sys_mod_count",
      "urgency",
    ],
    item_option_new_set: ["order", "sys_mod_count", "version"],
    kb_article_checklist_summary: ["aqi_score", "sys_mod_count"],
    kb_category: ["sys_mod_count"],
    kb_knowledge: [
      "helpful_count",
      "rating",
      "sys_mod_count",
      "sys_view_count",
      "use_count",
    ],
    kb_knowledge_base: ["article_validity", "order", "sys_mod_count"],
    kb_knowledge_summary: ["sys_mod_count"],
    kb_uc_can_contribute_mtom: ["sys_mod_count"],
    kb_uc_can_read_mtom: ["sys_mod_count"],
    kb_uc_cannot_contribute_mtom: ["sys_mod_count"],
    kb_uc_cannot_read_mtom: ["sys_mod_count"],
    kb_version: ["snapshot", "sys_mod_count"],
    ldap_server_config: [
      "connect_timeout",
      "listen_interval",
      "read_timeout",
      "sys_mod_count",
    ],
    m2m_sp_theme_css_include: ["order", "sys_mod_count"],
    m2m_sp_theme_js_include: ["order", "sys_mod_count"],
    pa_dashboards: ["order", "sys_mod_count", "visible_to"],
    par_component: ["sys_mod_count"],
    problem: [
      "escalation",
      "impact",
      "order",
      "priority",
      "problem_state",
      "reassignment_count",
      "related_incidents",
      "reopen_count",
      "route_reason",
      "state",
      "sys_mod_count",
      "urgency",
    ],
    sc_cat_item: ["cost", "order", "sc_ic_version", "sys_mod_count", "version"],
    sc_cat_item_delivery_plan: ["order", "sys_mod_count"],
    sc_cat_item_delivery_task: ["order", "sys_mod_count"],
    sc_cat_item_guide: [
      "cost",
      "order",
      "sc_ic_version",
      "sys_mod_count",
      "version",
    ],
    sc_cat_item_producer: [
      "cost",
      "order",
      "sc_ic_version",
      "sys_mod_count",
      "version",
    ],
    sc_catalog: ["sys_mod_count"],
    sc_category: ["order", "sys_mod_count"],
    sc_ordered_item_link: ["sys_mod_count"],
    sc_req_item: [
      "escalation",
      "impact",
      "order",
      "priority",
      "quantity",
      "reassignment_count",
      "route_reason",
      "state",
      "sys_mod_count",
      "urgency",
    ],
    sc_request: [
      "calendar_stc",
      "escalation",
      "impact",
      "order",
      "priority",
      "reassignment_count",
      "route_reason",
      "state",
      "sys_mod_count",
      "urgency",
    ],
    sc_task: [
      "calendar_stc",
      "escalation",
      "impact",
      "order",
      "priority",
      "reassignment_count",
      "route_reason",
      "state",
      "sys_mod_count",
      "urgency",
    ],
    sc_template: ["sys_mod_count"],
    service_offering: [
      "attestation_score",
      "cost",
      "fault_count",
      "install_status",
      "operational_status",
      "sys_mod_count",
    ],
    sla_condition_class: ["sys_mod_count"],
    sp_column: [
      "order",
      "size",
      "size_lg",
      "size_sm",
      "size_xs",
      "sys_mod_count",
    ],
    sp_container: ["order", "sys_mod_count"],
    sp_css_include: ["sys_mod_count"],
    sp_header_footer: ["sys_mod_count"],
    sp_instance: ["order", "sys_mod_count"],
    sp_instance_menu: ["order", "sys_mod_count"],
    sp_js_include: ["sys_mod_count"],
    sp_page: ["sys_mod_count"],
    sp_portal: ["sys_mod_count"],
    sp_rectangle_menu_item: ["order", "sys_mod_count"],
    sp_row: ["order", "sys_mod_count"],
    sp_theme: ["sys_mod_count"],
    sp_widget: ["sys_mod_count"],
    sys_alias: ["sys_mod_count"],
    sys_alias_templates: ["sys_mod_count"],
    sys_app_application: ["order", "sys_mod_count"],
    sys_app_category: ["default_order", "sys_mod_count"],
    sys_app_module: ["order", "sys_mod_count"],
    sys_attachment: [
      "chunk_size_bytes",
      "image_height",
      "image_width",
      "sys_mod_count",
    ],
    sys_auth_profile: ["sys_mod_count"],
    sys_auth_profile_basic: ["sys_mod_count"],
    sys_data_source: [
      "batch_size",
      "connection_timeout",
      "header_row",
      "ldapprobe_result_set_rows",
      "limit",
      "maximum_rows",
      "offset",
      "query_timeout",
      "sheet_name",
      "sheet_number",
      "sys_mod_count",
    ],
    sys_db_object: ["sys_mod_count"],
    sys_declarative_action_assignment: ["specificity", "sys_mod_count"],
    sys_dictionary: [
      "choice",
      "defaultsort",
      "max_length",
      "sizeclass",
      "sys_mod_count",
    ],
    sys_dictionary_override: ["sys_mod_count"],
    sys_element_mapping: ["sys_mod_count"],
    sys_email: ["sys_mod_count", "weight"],
    sys_email_attachment: ["sys_mod_count"],
    sys_email_digest_interval: ["sys_mod_count"],
    sys_email_layout: ["sys_mod_count"],
    sys_filter_option_dynamic: ["order", "sys_mod_count"],
    sys_flow_context: [
      "engine_major_version",
      "engine_version",
      "run_time",
      "sys_mod_count",
    ],
    sys_flow_data: ["sys_mod_count"],
    sys_hub_flow: ["authored_on_release_version", "sys_mod_count"],
    sys_hub_flow_base: ["authored_on_release_version", "sys_mod_count"],
    sys_hub_flow_block: ["sys_mod_count"],
    sys_hub_flow_component: ["sys_mod_count"],
    sys_hub_flow_logic_instance_v2: ["sys_mod_count"],
    sys_mailbox: ["sys_mod_count"],
    sys_metadata: ["sys_mod_count"],
    sys_notification_category: ["sys_mod_count"],
    sys_number: ["maximum_digits", "number", "sys_mod_count"],
    sys_perspective: ["order", "sys_mod_count"],
    sys_properties: ["sys_mod_count"],
    sys_push_notif_msg: ["sys_mod_count"],
    sys_relationship: ["sys_mod_count"],
    sys_report: [
      "chart_border_radius",
      "chart_border_width",
      "chart_height",
      "chart_subtitle_size",
      "chart_title_size",
      "chart_title_x_position",
      "chart_title_y_position",
      "chart_width",
      "decimal_precision",
      "donut_width_percent",
      "from",
      "funnel_neck_percent",
      "legend_border_radius",
      "legend_border_width",
      "lower_limit",
      "other_threshold",
      "sys_mod_count",
      "to",
      "upper_limit",
      "x_axis_grid_width",
      "x_axis_label_size",
      "x_axis_title_size",
      "y_axis_from",
      "y_axis_grid_width",
      "y_axis_label_size",
      "y_axis_title_size",
      "y_axis_to",
    ],
    sys_rest_message: ["sys_mod_count"],
    sys_rest_message_fn: ["sys_mod_count"],
    sys_retry_policy: ["count", "max_elapsed_time", "sys_mod_count"],
    sys_scope_privilege: ["sys_mod_count"],
    sys_script: ["order", "priority", "sys_mod_count"],
    sys_script_client: ["order", "sys_mod_count", "ui_type"],
    sys_script_email: ["sys_mod_count"],
    sys_script_fix: ["sys_mod_count"],
    sys_script_include: ["sys_mod_count"],
    sys_script_vtable: ["cache_ttl", "sys_mod_count"],
    sys_security_acl: ["sys_mod_count"],
    sys_security_acl_role: ["sys_mod_count"],
    sys_security_attribute: ["sys_mod_count"],
    sys_security_data_filter: ["sys_mod_count"],
    sys_security_operation: ["order", "sys_mod_count"],
    sys_security_type: ["sys_mod_count"],
    sys_ui_action: ["order", "sys_mod_count"],
    sys_ui_annotation_type: ["sys_mod_count"],
    sys_ui_application: ["order", "sys_mod_count"],
    sys_ui_element: ["position", "sys_mod_count"],
    sys_ui_form: ["sys_mod_count"],
    sys_ui_form_section: ["position", "sys_mod_count"],
    sys_ui_formatter: ["sys_mod_count"],
    sys_ui_list: ["position", "sys_mod_count"],
    sys_ui_list_control: ["sys_mod_count"],
    sys_ui_list_element: ["position"],
    sys_ui_macro: ["sys_mod_count"],
    sys_ui_module: ["order", "sys_mod_count"],
    sys_ui_page: ["sys_mod_count"],
    sys_ui_related_list: ["position", "sys_mod_count"],
    sys_ui_related_list_entry: ["position", "sys_mod_count"],
    sys_ui_section: ["sys_mod_count"],
    sys_ui_style: ["sys_mod_count"],
    sys_ui_view: ["sys_mod_count"],
    sys_user: [
      "calendar_integration",
      "failed_attempts",
      "notification",
      "sys_mod_count",
    ],
    sys_user_group: ["sys_mod_count"],
    sys_user_role: ["sys_mod_count"],
    sys_user_role_contains: ["sys_mod_count"],
    sys_ux_app_config: ["sys_mod_count"],
    sys_ux_app_route: ["order", "sys_mod_count"],
    sys_ux_macroponent: ["sys_mod_count"],
    sys_ux_page_registry: ["sys_mod_count"],
    sys_ux_screen: ["order", "sys_mod_count"],
    sys_ux_screen_type: ["sys_mod_count"],
    sys_variable_value: ["order", "sys_mod_count"],
    sys_ws_definition: ["sys_mod_count"],
    sys_ws_header: ["sys_mod_count"],
    sys_ws_header_map: ["sys_mod_count"],
    sys_ws_operation: ["sys_mod_count"],
    sys_ws_query_parameter: ["sys_mod_count"],
    sys_ws_query_parameter_map: ["sys_mod_count"],
    sys_ws_version: ["sys_mod_count", "version"],
    sysauto: ["offset_type", "repeat_every", "run_dayofmonth", "sys_mod_count"],
    sysauto_script: [
      "offset_type",
      "repeat_every",
      "run_dayofmonth",
      "sys_mod_count",
    ],
    sysevent_email_action: ["order", "sys_mod_count", "weight"],
    sysevent_email_style: ["sys_mod_count"],
    sysevent_email_template: ["sys_mod_count"],
    sysevent_register: ["derived_priority", "priority", "sys_mod_count"],
    sysevent_script_action: ["order", "sys_mod_count"],
    sysrule: ["order", "sys_mod_count"],
    sysrule_assignment: ["order", "sys_mod_count"],
    sysrule_view: ["order", "sys_mod_count"],
    sysrule_view_workspace: ["order", "sys_mod_count"],
    task: [
      "escalation",
      "impact",
      "order",
      "priority",
      "reassignment_count",
      "route_reason",
      "state",
      "sys_mod_count",
      "urgency",
    ],
    task_sla: ["sys_mod_count"],
    topic: ["order", "sys_mod_count"],
    user_criteria: ["sys_mod_count"],
    wf_context: ["activity_count", "activity_index", "sys_mod_count"],
    wf_workflow: ["sys_mod_count"],
  };
